### ISSUE TITLE
漫画柜大陆版无法使用

### ISSUE THREAD

**Issue by youniaogu** [youniaogu/MangaReader#1]
[https://www.mhgui.com/](https://www.mhgui.com/) 返回403，不知道是不是被ban了

有能打开或类似情况的朋友分享下吗

**Comment by xjp970208** [comment]
我打開是 https://www.manhuagui.com/
可正常使用

**Comment by youniaogu** [comment]
> 我打開是 https://www.manhuagui.com/ 可正常使用

这个地址应该是主站，可能你打开时不是大陆ip，漫画柜自动帮你跳过去

**Comment by youniaogu** [comment]
尝试了好几个ip还是403，应该不能用了，后续有更新再打开
