### ISSUE TITLE
为什么下载下来的图片是混乱的（条漫），一张图片里变成被分割后的重新组合

### ISSUE THREAD

**Issue by huanyuyunhuang** [youniaogu/MangaReader#100]
**非常感谢您填写错误报告！**

**以下是一些注意事项，请务必阅读**

- 提交报告前请检索相关 issues，避免重复提问
- 提交报告前请先尝试浏览器里访问原网站排除网络问题
- 请按下边 issues 模板要求提供相关信息，避免挤牙膏式提问

---

**问题描述**

**如何复现**

**错误信息**

**设备信息**

**Comment by youniaogu** [comment]
https://github.com/youniaogu/MangaReader/issues/101
