### ISSUE TITLE
导出路径能否自定义参数

### ISSUE THREAD

**Issue by Hoiyook** [youniaogu/MangaReader#104]
**现有功能改进还是新功能/插件提议？**
现有功能改进

**请简单描述下你的需求**
目前导出路径只有一个{chapter}的参数，还不可选。
每次导出一本漫画，都要手动改一下路径，不然会被覆盖。
建议能出一个自定义参数，比如漫画作者名称、漫画标题之类的。{username}/{title}

**解决方案**

**Comment by youniaogu** [comment]
那就把整个路径都放开编辑，然后添加占位符功能就好

**Comment by youniaogu** [comment]
[v0.7.0](https://github.com/youniaogu/MangaReader/releases/tag/v0.7.0) done
