### ISSUE TITLE
[我又来了]开始定时功能后手动翻页后重置计时器

### ISSUE THREAD

**Issue by XianYuDaXian** [youniaogu/MangaReader#106]
**现有功能改进还是新功能/插件提议？**
开始定时功能后手动翻页后重置计时器
**请简单描述下你的需求**
有的时候翻到页大跨页没什么对话的页面，就手动翻页，结果下一页又充满了对话，计时器没有重置就导致没看完就翻页了，优化下使用感更好

**解决方案**
开始定时功能后手动翻页后重置计时器

**Comment by youniaogu** [comment]
[v0.7.0](https://github.com/youniaogu/MangaReader/releases/tag/v0.7.0) done
