### ISSUE TITLE
打开app的动画感觉有一点不连贯

### ISSUE THREAD

**Issue by Letter0** [youniaogu/MangaReader#107]
感觉打开app的动画感觉有一点不连贯，动画图案没有到屏幕最右边就直接转到了主页面，附上视频

https://github.com/youniaogu/MangaReader/assets/83254135/f2c2791a-6bf1-4955-bdb9-6487ec0f1941

**Comment by youniaogu** [comment]
这是因为 app 初始化速度比开屏动画还要快的原因...，等加一些漫画收藏有数据后就不会有这个问题了
