### ISSUE TITLE
问题反馈、优化以及新插件提议

### ISSUE THREAD

**Issue by yuduotianguang** [youniaogu/MangaReader#108]
问题反馈：无cf，禁漫无法显示，如视频
2.14补充，换了个网，能过cf，但依然不行

https://github.com/youniaogu/MangaReader/assets/104707441/2f8f256b-dbe7-48e9-af1d-e547b072d0af

优化：
1.拷贝漫画是可以调节分辨率的，希望可以加上或者把默认分辨率调到最高
2.设置里插件的顺序希望可以自己调整

新插件提议：以下均不需要代理
1.国漫最快，但有水印，Cola漫画https://www.colamanga.com/
2.有国漫，日漫多，coco漫画https://cocomanga.xyz/
3.国漫较快，有日漫，漫画1234http://m.gmh1234.com/
4.国漫较快，但有水印，日漫多，有R18（都是jm的，可以作为jm无需代理的替代)，漫蛙https://fuw11.cc/mw666
下面几个先不急
5.日漫多，92漫画http://www.92mh.com/
6.国漫较慢，但质量更高，古风漫画https://www.gufengmh.com/
7.国漫较慢，但质量更高，喵上漫画http://miaoshangmanhua.com/
无需代理比较好的都在这了

**Comment by youniaogu** [comment]
拷贝漫画只有一个是否用 webp 图片格式，但那个有人反馈 ios 版本过低 webp 显示白屏就没用了

**Comment by yuduotianguang** [comment]
> 拷贝漫画没有修改图片质量的 header 吧，我只知道哔咔漫画有

不懂这个，但拷贝确实可以改分辨率，保存图片就看到差很多了

**Comment by yuduotianguang** [comment]
> 拷贝漫画只有一个是否用 webp 图片格式，但那个有人反馈 ios 版本过低 webp 显示白屏就没用了

![QQ图片20240213173626](https://github.com/youniaogu/MangaReader/assets/104707441/49c49ce8-83fc-4748-ab43-819a9c925f6c)
![QQ图片20240213173631](https://github.com/youniaogu/MangaReader/assets/104707441/9565e700-5193-415f-99cf-8724e3ede8b7)
![QQ图片20240213173634](https://github.com/youniaogu/MangaReader/assets/104707441/351aac2c-fa7c-438a-a0cf-cc6c4b48a7d7)
这俩图分辨率差特别多了，肯定能改我才会说的

**Comment by youniaogu** [comment]
知道了，他们 cdn 上的功能

[https://hi77-overseas.mangafuna.xyz/yunibianzhuidepaomo/631e2/1647229184270001.jpg.c800x.jpg](https://hi77-overseas.mangafuna.xyz/yunibianzhuidepaomo/631e2/1647229184270001.jpg.c800x.jpg)
[https://hi77-overseas.mangafuna.xyz/yunibianzhuidepaomo/631e2/1647229184270001.jpg.c1500x.jpg](https://hi77-overseas.mangafuna.xyz/yunibianzhuidepaomo/631e2/1647229184270001.jpg.c1500x.jpg)

晚点改一下

**Comment by youniaogu** [comment]
[v0.7.0](https://github.com/youniaogu/MangaReader/releases/tag/v0.7.0)，修复了 JMC 无法使用的问题，COPY 分辨率修改至最高

+ 排序这个之前也有人提过，我建了个新 issues #109，尽量下个版本更新
+ 漫画网站有几个挺好的，而且不需要代理和 CF，不过目前插件已经很多了，不想继续增加维护成本，这几个插件我先记下来，有需要再考虑加进去

关于上面说的插件多，维护成本高，我想的是后面开个 issues 或投票，讨论哪些插件要删掉，然后替换为哪个插件，插件数尽量维持在一定范围内，这样我维护起来也轻松

**Comment by yuduotianguang** [comment]
> [v0.7.0](https://github.com/youniaogu/MangaReader/releases/tag/v0.7.0)，修复了 JMC 无法使用的问题，COPY 分辨率修改至最高
> 
> + 排序这个之前也有人提过，我建了个新 issues #109，尽量下个版本更新
> + 漫画网站有几个挺好的，而且不需要代理和 CF，不过目前插件已经很多了，不想继续增加维护成本，这几个插件我先记下来，有需要再考虑加进去
> 
> 关于上面说的插件多，维护成本高，我想的是后面开个 issues 或投票，讨论哪些插件要删掉，然后替换为哪个插件，插件数尽量维持在一定范围内，这样我维护起来也轻松

拷贝这个，好像还是差很多，不知道什么原因
插件主要是因为看日漫插件基本都需要代理，而且db和bz两个有点冗余了（要代理而且还不如不要代理的网站)。然后看国漫的插件仅有包子一个，但是这网站有拦腰截断的横幅很影响观感
