### ISSUE TITLE
允许修改插件顺序

### ISSUE THREAD

**Issue by youniaogu** [youniaogu/MangaReader#109]
**现有功能改进还是新功能/插件提议？**

现有功能改进

**请简单描述下你的需求**

能够自定义插件的顺序

**解决方案**

在插件页面增加拖拽排序

**Comment by VickyRain** [comment]
插件的功能到底是什么？
我都把拷贝漫画关闭了，只打开了漫画柜（已挂代理，确定可以访问），搜索还是会搜到拷贝漫画的源。

**Comment by yuduotianguang** [comment]
> 插件开关到底能控制什么？
> 我都把拷贝漫画的开关关闭了，只打开了漫画柜（已挂代理，确定可以访问），搜索还是会搜到拷贝漫画的源。

有没有一种可能，不止漫画柜，基本大部分别的网站大部分都是从拷贝那来的

**Comment by youniaogu** [comment]
@yuduotianguang 清晰度后面我再去看下把

下次更新的话会去掉漫画 db（默认禁用不维护），然后加个新的源（不需要代理并且不需要 cf 的）

**Comment by yuduotianguang** [comment]
> @yuduotianguang 清晰度后面我再去看下把
> 
> 下次更新的话会去掉漫画 db（默认禁用不维护），然后加个新的源（不需要代理并且不需要 cf 的）

那行加漫神吧日漫国漫都很多

**Comment by youniaogu** [comment]
#117

**Comment by youniaogu** [comment]
[v0.7.1](https://github.com/youniaogu/MangaReader/releases/tag/v0.7.1)
