### ISSUE TITLE
“响应失败：请求超过了限速。”希望可以自动完成拷贝源书架的刷新

### ISSUE THREAD

**Issue by hot36952** [youniaogu/MangaReader#11]
书一旦多起来，每刷新10+本，又要等待45秒再手动刷新，希望可以自动等候完成所有的刷新。
如果能够有个像帐号书架列表整个刷新那样更好。

**Comment by youniaogu** [comment]
谢谢反馈，下次更新我会增加等待时间（默认和根据copy那边返回的时间）以及重试次数。

再后续会考虑更新列表以及下载列表相关

**Comment by youniaogu** [comment]
fixed [v0.3.2](https://github.com/youniaogu/MangaReader/releases/tag/v0.3.2)
