### ISSUE TITLE
漫画效果

### ISSUE THREAD

**Issue by Calcium20030106** [youniaogu/MangaReader#110]
大佬，韩漫看得太难受了，能不能加个条漫的选项？

**Comment by youniaogu** [comment]
点击这里切换，更多的可以看[这里](https://github.com/youniaogu/MangaReader?tab=readme-ov-file#%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97)
<img src="https://github.com/youniaogu/MangaReader/assets/13073995/bfafa22e-0bb0-4d1e-8b26-53fe6e4c95e9" width="360" />
