### ISSUE TITLE
下载章节后没有在指定目录生成文件，导出显示授权失败

### ISSUE THREAD

**Issue by VickyRain** [youniaogu/MangaReader#112]
三星S22 Ultra，Android 14，OneUI6.0，原生系统未root，不支持SD卡。

首先看说明里的截图如没明白“下载”和“导出”的区别。下载的箭头指向文字是包含了下载和转存到指定目录，而导出的箭头指向文字只说路径可以修改？但实际操作似乎不是这个意思？到底哪个按钮是把图片转存到配置里的指定目录？

目前的情况是这样的：
点击“下载”，无论是使用默认路径还是自定义路径（包括改为/storage/emulated/0/DCIM这种路径），下载后都没有在指定目录中生成章节文件夹和文件。Photos and videos权限已经手动授予，但还是没有成功，无任何错误提示。
下载本身应该确实是成功了，实时下载速度和流量使用上可以看出来，APP缓存也增加了。

下载完成（如果确实是成功了的话）后点击“导出“”，先显示toast“导出中...”，然后马上在下方显示“授权失败”，这个提示应该是来自于checkAndroidPermission()获取外置SD卡写权限失败？但三星S22 Ultra并不支持外置SD卡。

选择下载的漫画来源是“拷贝漫画”，不过这个问题应该和源没关系？

以及，为什么把拷贝漫画插件关闭了（事实上我只留下了漫画柜，并且确定挂上了梯子可以正常访问），搜索到的源仍然还是拷贝漫画？

**Comment by youniaogu** [comment]
有空时我去复现一下，然后关闭插件只是不显示在右上角的选择框里，具体在用哪个插件要看右上角

**Comment by VickyRain** [comment]
> 有空时我去复现一下，然后关闭插件只是不显示在右上角的选择框里，具体在用哪个插件要看右上角

ok，谢谢~

**Comment by youniaogu** [comment]
fixed [v0.7.4](https://github.com/youniaogu/MangaReader/releases/tag/v0.7.4)
