### ISSUE TITLE
拷贝漫画源问题

### ISSUE THREAD

**Issue by EmiyaGm** [youniaogu/MangaReader#114]
https://www.mangacopy.com/

地址应该是换成这个了，原来的那个现在是进不去了

**Comment by youniaogu** [comment]
现在用的就是这个地址，遇到什么问题了吗

**Comment by EmiyaGm** [comment]
> 现在用的就是这个地址，遇到什么问题了吗

那就没问题了应该，我看 readme 上面指向的地址好像不是现在这个地址

**Comment by youniaogu** [comment]
@EmiyaGm 已更新 readme
