### ISSUE TITLE
搜索功能只能搜索拷贝漫画的源

### ISSUE THREAD

**Issue by holystool** [youniaogu/MangaReader#115]
如题，ios端，搜索界面只能搜索拷贝漫画的源，其他源都只能在插件界面里作为普通网页浏览。
![IMG_4741](https://github.com/youniaogu/MangaReader/assets/42994427/3f025b05-dfe6-4268-846d-ad05b089342d)
![IMG_4742](https://github.com/youniaogu/MangaReader/assets/42994427/e0b1f4ac-0958-4781-b848-a9d01de4d6a8)

**Comment by VickyRain** [comment]
看到右上角的“copy”没有，点击那个列出所有插件，选想要的就能切到别的源了，那个copy的意思就是当前源是拷贝漫画……
我也是在另一个issue里提到这个问题以后，开发者回复才知道的
因为它既不显示成按钮，也没有带类似于列表的图标，并且还是英文，导致一开始直接忽略掉了，虽然readme的cloudflare 校验那节第一张图里就有

**Comment by holystool** [comment]
> 看到右上角的“copy”没有，点击那个列出所有插件，选想要的就能切到别的源了，那个copy的意思就是当前源是拷贝漫画…… 我也是在另一个issue里提到这个问题以后，开发者回复才知道的 因为它既不显示成按钮，也没有带类似于列表的图标，并且还是英文，导致一开始直接忽略掉了，虽然readme的cloudflare 校验那节第一张图里就有

果然可以，非常感谢！

**Comment by youniaogu** [comment]
暂定下次更新优化下交互提示

**Comment by holystool** [comment]
> 暂定下次更新优化下交互提示

可以考虑为收藏夹增加一个分组功能不？想把禁漫和其他分开一下

**Comment by youniaogu** [comment]
@holystool 收藏夹已经有 #70，相关讨论可以在这个 issues 里
