### ISSUE TITLE
拷貝漫畫載入異常

### ISSUE THREAD

**Issue by kenwang92** [youniaogu/MangaReader#116]
**非常感谢您填写错误报告！**

**以下是一些注意事项，请务必阅读**

- 提交报告前请检索相关 issues，避免重复提问
- 提交报告前请先尝试浏览器里访问原网站排除网络问题
- 请按下边 issues 模板要求提供相关信息，避免挤牙膏式提问

---

**问题描述**

拷貝漫畫初次點入的第二張圖片載入異常緩慢，如果先往下滑到後面頁數再滑回去又會加載出來，只有初次點入的集數會發生，往下接著看的接續集數則不會發生，上一次更新前已發現此問題。

另外，有時候app載入漫畫後會嚴重卡頓，甚至無法操作，原先以為是網站加載緩慢導致，但是之前版本加載緩慢，但app不會卡頓，可順場往回滑動，即使下面圖片處於加載中的狀態。

**如何复现**

隨便點一部拷貝漫畫可復現
https://github.com/youniaogu/MangaReader/assets/51316165/ed1e1780-c287-4ba4-8c60-5b2413164393

**错误信息**

無錯誤

**设备信息**

設備：oneplus 1+6t
app版本：v0.7.0

**Comment by youniaogu** [comment]
有可能同时请求太多图片了，第二次点进去不卡是因为有缓存了

**Comment by youniaogu** [comment]
fixed [v0.7.1](https://github.com/youniaogu/MangaReader/releases/tag/v0.7.1)
