### ISSUE TITLE
解析增加页数跳转

### ISSUE THREAD

**Issue by specked2527** [youniaogu/MangaReader#119]
**现有功能改进还是新功能/插件提议？**
解析增加页数跳转
**请简单描述下你的需求**
解析增加页数跳转，目前只能无限下滑，不能通过页数跳转（分类主页，不是阅读器的）

**解决方案**
参考https://github.com/wgh136/PicaComic

**Comment by youniaogu** [comment]
不是每个网站的数据都带有分页参数，没办法做到很完美，所以不考虑
