### ISSUE TITLE
fixed [v0.3.2](https://github.com/youniaogu/MangaReader/releases/tag/v0.3.2)

### ISSUE THREAD

**Issue by hot36952** [youniaogu/MangaReader#12]
fixed [v0.3.2](https://github.com/youniaogu/MangaReader/releases/tag/v0.3.2)

_Originally posted by @youniaogu in https://github.com/youniaogu/MangaReader/issues/11#issuecomment-1352510160_
      
0.3.1的ipa有个属性是person.youniaogu.MangaReader
0.3.2的ipa这个属性是person.jigu.MangaReader
是不是因为这个原因导致安装0.3.2时，不是覆盖安装，是新建一个，继而导致书架为空。
顺便提一个建议，增加一个书架备份&导入功能，方便iphone和ipad之间同步书架。

**Comment by youniaogu** [comment]
抱歉，应该是我打包时选错了，等会我重新上传一份

**Comment by youniaogu** [comment]
上传好了，记得刷新缓存，注意文件右边的更新时间
