### ISSUE TITLE
IOS端下载的漫画怎么删除掉？在哪里删除呢？

### ISSUE THREAD

**Issue by JarryChou** [youniaogu/MangaReader#122]
**非常感谢您填写错误报告！**

**以下是一些注意事项，请务必阅读**

- 提交报告前请检索相关 issues，避免重复提问
- 提交报告前请先尝试浏览器里访问原网站排除网络问题
- 请按下边 issues 模板要求提供相关信息，避免挤牙膏式提问

---

**问题描述**

**如何复现**

**错误信息**

**设备信息**

**Comment by youniaogu** [comment]
About 页面删除图片缓存就好了
