### ISSUE TITLE
包子漫畫驗證異常

### ISSUE THREAD

**Issue by kenwang92** [youniaogu/MangaReader#123]
**非常感谢您填写错误报告！**

**以下是一些注意事项，请务必阅读**

- 提交报告前请检索相关 issues，避免重复提问
- 提交报告前请先尝试浏览器里访问原网站排除网络问题
- 请按下边 issues 模板要求提供相关信息，避免挤牙膏式提问

---

**问题描述**
包子漫畫驗證過不了，一直轉圈圈後又再次要求按框框
![Screenshot_20240325-014301.jpg](https://github.com/youniaogu/MangaReader/assets/51316165/3ec2a3d8-aead-4091-a961-359a146ad0d8)

**如何复现**
按下包子漫畫插件打開驗證頁面

**错误信息**
無

**设备信息**
Oneplus 1+6t android 11
2024-03-10  v0.7.1

**Comment by youniaogu** [comment]
试了下，安卓下确实失效了，可能要改下 ua

**Comment by youniaogu** [comment]
done [v0.7.2](https://github.com/youniaogu/MangaReader/releases/tag/v0.7.2)
