### ISSUE TITLE
希望在翻頁模式能選擇關閉翻頁動畫

### ISSUE THREAD

**Issue by kenwang92** [youniaogu/MangaReader#124]
**现有功能改进还是新功能/插件提议？**

**请简单描述下你的需求**

為了在閱讀器使用，希望在翻頁模式能選擇關閉翻頁動畫

**解决方案**

加一個翻頁動畫的開關

**Comment by youniaogu** [comment]
[v0.7.3](https://github.com/youniaogu/MangaReader/releases/tag/v0.7.3) done
