### ISSUE TITLE
拷贝源好像寄了，开始收费导致大部分漫画都

### ISSUE THREAD

**Issue by bakamoon** [youniaogu/MangaReader#125]
**非常感谢您填写错误报告！**

**以下是一些注意事项，请务必阅读**

- 提交报告前请检索相关 issues，避免重复提问
- 提交报告前请先尝试浏览器里访问原网站排除网络问题
- 请按下边 issues 模板要求提供相关信息，避免挤牙膏式提问

---

**问题描述**
拷贝源好像寄了，开始收费导致大部分漫画都404了
**如何复现**

**错误信息**

**设备信息**

**Comment by youniaogu** [comment]
有部分漫画可能被下架了，先观察一下

**Comment by youniaogu** [comment]
https://www.copymanga.site/comic/zangsongdefulilian

**Comment by shibuyameltdown** [comment]
https://www.colamanga.com/
这有一个源专门抓正版化漫画，但是要非大陆ip，不然热门的会被隐藏

> https://www.copymanga.site/comic/zangsongdefulilian
