### ISSUE TITLE
条漫显示模糊，可能因为图像显示lib有分辨率限制

### ISSUE THREAD

**Issue by Silver7758** [youniaogu/MangaReader#126]
我判断目前应该不需要更多信息就能直接复现此bug

范例漫画名：決定退出勇者隊伍

![IMG_20240330_112204](https://github.com/youniaogu/MangaReader/assets/46341546/8f0f35f9-37b3-4368-b97d-773fa7e95f6b)

![IMG_20240330_112235](https://github.com/youniaogu/MangaReader/assets/46341546/48dba063-d2d4-424b-95b0-0e49424683ce)

**Comment by 92912805** [comment]
可以考虑预处理图像，将其切割成小块tile，并根据滑动位置拼凑显示相邻tile

**Comment by youniaogu** [comment]
这个应该是网络问题，也可能跟代码里写的 cdn hostname 有关

目前在用的 `i` 在漫画柜那边权重是 0.1 最低的，下个版本会按权重去随机拿 hostname（跟网站逻辑保持一致）

<img width="335" alt="image" src="https://github.com/youniaogu/MangaReader/assets/13073995/5aad1d3d-75ea-43bc-ba17-91f77f64ebe8">

**Comment by youniaogu** [comment]
这个比较糊的图片应该是漫画柜那边的 fallback，加载失败的时候就会显示这个

**Comment by youniaogu** [comment]
done [v0.7.2](https://github.com/youniaogu/MangaReader/releases/tag/v0.7.2)

**Comment by youniaogu** [comment]
有段逻辑写错了，晚上重新打包

**Comment by Silver7758** [comment]
安装了v0.7.2。

目前仍有条漫模糊的问题，症状与原描述相同。
