### ISSUE TITLE
最新版漫画柜源加载不了图片，旧版本正常

### ISSUE THREAD

**Issue by XianYuDaXian** [youniaogu/MangaReader#128]
**非常感谢您填写错误报告！**

**以下是一些注意事项，请务必阅读**

- 提交报告前请检索相关 issues，避免重复提问
- 提交报告前请先尝试浏览器里访问原网站排除网络问题
- 请按下边 issues 模板要求提供相关信息，避免挤牙膏式提问

---

**问题描述**
最新版漫画柜源加载不了图片，旧版本正常
**如何复现**

**错误信息**

**设备信息**
ios和安卓都是

**Comment by youniaogu** [comment]
更新了安装包
