### ISSUE TITLE
嗨皮漫画的验证一直无法通过

### ISSUE THREAD

**Issue by fatesses** [youniaogu/MangaReader#129]
嗨皮漫画的验证一直无法通过，如果用浏览器打开是可以通过的，内置插件里，其他的插件都能通过验证，唯独嗨皮漫画的要不停验证

**Comment by Silver7758** [comment]
猜测是cloudflare检测到是Webview，网站管理员不允许导致，因为换其它浏览器都没有这个问题。

**Comment by youniaogu** [comment]
fixed [v0.7.3](https://github.com/youniaogu/MangaReader/releases/tag/v0.7.3)

之前偷懒，安卓用了 ios 的 ua，导致校验失败

**Comment by rucswax** [comment]
> fixed [v0.7.3](https://github.com/youniaogu/MangaReader/releases/tag/v0.7.3)
> 
> 之前偷懒，安卓用了 ios 的 ua，导致校验失败

除了嗨皮漫画，我也试了一些网站
1. [https://mvnrepository.com/](https://mvnrepository.com/)
2. [https://apkmirror.com/](https://apkmirror.com/)
3. [https://apkcombo.com/](https://apkcombo.com/)

发现 UA 若不是默认的话，则会无法通过 CloudFlare 验证。有个链接和这个问题有关，[https://github.com/aniyomiorg/aniyomi/discussions/1416](https://github.com/aniyomiorg/aniyomi/discussions/1416)

而不同设备的默认 UA 是不同的，所以感觉把 userAgent 的值改成一个变量好过将它固定为某个字符串吧。
[https://github.com/youniaogu/MangaReader/blob/e6f59627cc7c9774af4b3816100bc24520f926b8/src/plugins/happy.ts#L251-L254](https://github.com/youniaogu/MangaReader/blob/e6f59627cc7c9774af4b3816100bc24520f926b8/src/plugins/happy.ts#L251-L254)
