### ISSUE TITLE
拷贝源只能看五页

### ISSUE THREAD

**Issue by AKItan117** [youniaogu/MangaReader#13]
拷贝源只能看五页了

**Comment by youniaogu** [comment]
看了下，拷贝漫画H5那边强制要求下载app才能看，只能改成从web拿图片

**Comment by youniaogu** [comment]
不过我最近中招阳了，得休息一段时间，你们先拿其他源顶一顶

**Comment by youniaogu** [comment]
Fixed [v0.3.3](https://github.com/youniaogu/MangaReader/releases/tag/v0.3.3)

**Comment by AKItan117** [comment]
感谢(ﾉ´▽｀)ﾉ♪
