### ISSUE TITLE
happy源封面无法显示

### ISSUE THREAD

**Issue by holystool** [youniaogu/MangaReader#130]
---

**问题描述**
happy源无论是搜索界面还是home书架界面，都无法显示封面，删除app重装也无法解决。漫画打开后内容页正常。

**设备信息**
iPhone13pro，ios17.4.1，app版本从前3、4版本开始一直如此，目前是最新的0.7.2

![IMG_7019](https://github.com/youniaogu/MangaReader/assets/42994427/ed0dcc2b-fb06-41d4-ae80-998ae0b738c1)
![IMG_7020](https://github.com/youniaogu/MangaReader/assets/42994427/fd6c5967-353b-4c4d-970c-2dc418896f0b)

**Comment by youniaogu** [comment]
安卓和苹果都没法复现，可能是网络问题，建议切换下代理
