### ISSUE TITLE
希望阅读时状态栏沉浸

### ISSUE THREAD

**Issue by nuptzhangquan** [youniaogu/MangaReader#133]
**现有功能改进还是新功能/插件提议？**
阅读漫画时可以状态栏沉浸 隐藏最上面时间 电量等信息的状态栏
**请简单描述下你的需求**
阅读漫画时可以状态栏沉浸 隐藏最上面时间 电量等信息的状态栏

**解决方案**

增加状态栏沉浸开关

**Comment by youniaogu** [comment]
点屏幕中间可以切换

**Comment by nuptzhangquan** [comment]
> 点屏幕中间可以切换

![Screenshot_20240418_231854_MangaReader](https://github.com/youniaogu/MangaReader/assets/29009012/af03d7bb-56cc-4c5e-8bfe-e8d6a23d3d6a)
你好 我的意思是手机系统的状态栏就是图片上最上面的一栏希望可以沉浸 点屏幕中间沉浸的是应用内的状态栏对系统状态栏没有作用
