### ISSUE TITLE
希望能隱藏系統列

### ISSUE THREAD

**Issue by kenwang92** [youniaogu/MangaReader#139]
**现有功能改进还是新功能/插件提议？**

**请简单描述下你的需求**

希望可以隱藏android狀態列
![Screenshot_20240422-154637](https://github.com/youniaogu/MangaReader/assets/51316165/e7fba6c8-f3b4-48d4-b318-598d920f08d1)

希望載入的彈跳gif動畫能關閉或變成靜態的空白頁

**解决方案**

有開關可以調整

**Comment by youniaogu** [comment]
done
