### ISSUE TITLE
苹果自签了也没法安装

### ISSUE THREAD

**Issue by shibuyameltdown** [youniaogu/MangaReader#14]
ios16.2，用爱思助手自签的

**Comment by youniaogu** [comment]
安装时有报错什么的吗

**Comment by shibuyameltdown** [comment]
安装包验证失败或设备未越狱
![YP`1`B6@RJ{4F8AV@%YS}ZE](https://user-images.githubusercontent.com/78797438/210725123-ea4c5675-217c-402d-a2b9-18f6291a5230.png)

**Comment by shibuyameltdown** [comment]
刚才试了其他软件是可以的

**Comment by youniaogu** [comment]
应该是爱思助手的问题，刚试了下签名失败
<img src="https://user-images.githubusercontent.com/13073995/210725397-daf1c29e-6baa-473b-9738-79fa25865bfc.png" width="600" />
换成AltStore没问题，装的最新版本v0.3.3
<img src="https://user-images.githubusercontent.com/13073995/210725401-130d84c4-974c-464a-a7fa-07eb3cffd4e3.jpg" width="200" />

**Comment by shibuyameltdown** [comment]
好的感谢

**Comment by shibuyameltdown** [comment]
破案了。。。不是爱思助手的问题，是非开发者只能侧载3个app，我已经侧载了3个了

**Comment by youniaogu** [comment]
> 破案了。。。不是爱思助手的问题，是非开发者只能侧载3个app，我已经侧载了3个了

这个我也是第一次知道，学到了
