### ISSUE TITLE
请添加删除漫画功能

### ISSUE THREAD

**Issue by kiana-why** [youniaogu/MangaReader#145]
**现有功能改进还是新功能/插件提议？**
现有功能改进

**请简单描述下你的需求**
我需要知道下载后的漫画文件在哪个地方，或者提供下载目录设置
我还需要提供漫画删除功能，以防下载漫画过多占据手机内存

**解决方案**
1.
我本以为导出目录和下载目录是同一个，但我无法在导出目录中找到下载文件，所以我猜想下载目录是和导出目录不同的文件夹，就在code中找了一下
2.
![截图 2024-05-13 17-43-15](https://github.com/youniaogu/MangaReader/assets/118311033/067a07e1-bed9-4e87-8e06-68d18b213c3f)
我观察到code中有设置下载目录，但我无法在手机中找到该目录，无法通过手动寻找目录删除漫画，（也有可能是我位置找错了，如果是这种情况请指导我一下）
3.
我觉得可以用设置导出目录的方式设置一下下载目录，或是直接将导出目录和下载目录合并
4.
为了方便起见也可以设置最大缓存之类的东西
5.
可以介绍一下本软件在该issue之前是怎么打算解决存储问题的吗？

**Comment by youniaogu** [comment]
1. 下载只是把漫画缓存而已，导出则会把这个缓存复制到指定目录
2. About 页面安卓可以修改导出目录（主页 Home Icon 点击进去）
3. 见第 2 条，目录支持导出模版，详细见 Release log
4. 未设置最大缓存，但About 页面可以清图片缓存
5. 其他问题可以翻下 readme 或更新日志

**Comment by kiana-why** [comment]
> 1. 下载只是把漫画缓存而已，导出则会把这个缓存复制到指定目录
> 2. About 页面安卓可以修改导出目录（主页 Home Icon 点击进去）
> 3. 见第 2 条，目录支持导出模版，详细见 Release log
> 4. 未设置最大缓存，但About 页面可以清图片缓存
> 5. 其他问题可以翻下 readme 或更新日志

1.
谢谢回答
2.
我在下载完漫画之后清了缓存，发现漫画还是已下载状态，所以才会好奇下载好的漫画怎么办
3.
我觉得缓存和下载功能应分开，从应用逻辑上来说，下载是为了保留，缓存是为了加速
所以我才提议将导出和下载合并，因为目的都是为了"保留"
缓存应是为了“提前加载”
4.
如果应用逻辑是通过清除缓存来清除已下载文件，那么要清除“除已下载文件以外的其他需要清除的文件”该怎么办
换句话说：如何清除“想要清除的文件”，同时保留“不想清除的文件”
5.
我同时也注意到导出漫画还是没有解决“文件夹名称相同”的问题
只能通过用户自己手动设置目录来解决
如果能够在“缓存”时互不影响，那么应该没理由不能解决“移动缓存文件夹”的运行逻辑
6.
关于“
About 页面安卓可以修改导出目录（主页 Home Icon 点击进去）
见第 2 条，目录支持导出模版，详细见 Release log
”
其实我是想知道"下载目录"，即“缓存目录”的位置，而不是“导出目录”的位置

**Comment by youniaogu** [comment]
2. 因为没有重置状态
3. 你提的“缓存”和“下载”是一样的，都是为了提前加载图片防止 loading 的策略
4. 目前还不支持这个功能
5. 缓存里是用 hash 去区分，实际上**导出路径模板**可以通过配置实现类似的效果，详细看[这里](https://github.com/youniaogu/MangaReader/releases/tag/v0.7.2)
6. https://github.com/youniaogu/MangaReader/blob/f114be4c3576dc7959a9bf1f308e960d5ce98b31/index.js#L24 这个目录没有 Root 是没法看到的，只能在 App 内使用

**Comment by kiana-why** [comment]
> 2. 因为没有重置状态
> 3. 你提的“缓存”和“下载”是一样的，都是为了提前加载图片防止 loading 的策略
> 4. 目前还不支持这个功能
> 5. 缓存里是用 hash 去区分，实际上**导出路径模板**可以通过配置实现类似的效果，详细看[这里](https://github.com/youniaogu/MangaReader/releases/tag/v0.7.2)
> 6. https://github.com/youniaogu/MangaReader/blob/f114be4c3576dc7959a9bf1f308e960d5ce98b31/index.js#L24
>     这个目录没有 Root 是没法看到的，只能在 App 内使用

1.我用了mt管理器（有root状态）依然无法找到缓存目录
2.有没有可能重新设置“缓存”目录，我注意到在about界面备份时会导出文件到android的data目录，我看很多软件都是用这个目录当缓存目录，能够换个地方存储缓存文件吗？
3.删除漫画的功能是必不可少的，不然用户只能用接近“重装”的方式来释放内存
4.至于导出模板我看到了，更进一步，在“缓存”时只需要hash区分漫画，在“导出”时可以让用户自己设置表单内容
或者如果导出和缓存能够做到一起不就更方便了吗？如果能够用库维持：漫画网站——漫画名——作者——hash目录.... 是不是会更方便一点

谢谢你的回答，我也是最近才在用你的软件，但没有删除漫画的功能让我很奇怪，一般来说漫画软件有两种：一种是不能下载漫画的，这种软件一般都是web套壳，跟在线看差不多，就没有必要删除漫画。第二种就是可以下载漫画的，可以下载漫画的必有删除功能。
我也不知道其他人都是怎么在用，难道下载的漫画越来越多都没有想过下一步怎么办吗？

**Comment by youniaogu** [comment]
备份只是在 Dirs.CacheDir 目录下生成 .txt 文件然后分享出去，并不会指定 data 目录

更多的导出模版可以翻以前的更新日志，你举例的这几个已经有了，只是没空更新 readme 而已

这个 app 的数据分**漫画**和**图片**两部分

漫画是指加载回来的标题、作者和图片 URL，只要把漫画取消收藏就会去掉相关的数据，图片则是把 URL 加载完存在 app 缓存里的，这部分 about 页面可以全部清除

然后也有另外的，就是备份生成的 txt 文件以及没有删，这个没有考虑到

所以下载漫画越来越多导致内存不够用，在 about 页面把图片缓存清掉就好了，这部分基本上占了 80% 的大小，至于备份文件下次找机会提供入口删除

**Comment by kiana-why** [comment]
> 漫画是指加载回来的标题、作者和图片 URL，只要把漫画取消收藏就会去掉相关的数据，图片则是把 URL 加载完存在 app 缓存里的，这部分 about 页面可以全部清除

1.
经过实验，漫画数据只有在取消收藏后清除缓存才能被删除
如果有这个逻辑在那么就可以暂时不用想办法增加删除功能了
逻辑上来说可能无法删除个别漫画章节，因为只能整个漫画删除（但一般人可能不需要删除个别章节）
