### ISSUE TITLE
状态栏显示问题

### ISSUE THREAD

**Issue by yaoylong** [youniaogu/MangaReader#147]
作者你好，使用设备是ios的，想提议一下，能否增加一个设置，可打开或关闭状态栏显示。

**Comment by raoxiongwen** [comment]
https://github.com/youniaogu/MangaReader/assets/75081273/8dff9aed-cbc1-41c6-959f-86af5756525a

@youniaogu没错，又是我，哈哈哈， 我增加了这个功能，但我不知道这样是否符合你的预期，如果可以的话，我可以发起pr

**Comment by youniaogu** [comment]
@raoxiongwen 不用单独开关，跟 showExtra 状态走就好了，可以麻烦提个 PR 吗

这个问题 IOS 上没有所以没怎么在意 sorry

**Comment by youniaogu** [comment]
done
