### ISSUE TITLE
能加个自动下一话功能吗

### ISSUE THREAD

**Issue by shibuyameltdown** [youniaogu/MangaReader#15]
目前的下一话按钮得从被窝里伸出另一只手才能操作😢

**Comment by youniaogu** [comment]
最后一页点击右侧进入下一话（竖屏模式可能不太准确）
长按进入下一话
三击进入下一话

打算这里面选一种实现，加在下次更新里，有什么好的idea也可以分享下

**Comment by shibuyameltdown** [comment]
第一种和第二种我觉得都挺好的，感谢🙇
顺带提一下更新提示可以实现吗，就是在书架页面看到封面有个new之类的

**Comment by youniaogu** [comment]
@shibuyameltdown  更新提示已经有了，在首页右上角批量更新

如果是推送通知的话，我还没找到稳定后台执行更新的方法

**Comment by shibuyameltdown** [comment]
好的，明白了

**Comment by hot36952** [comment]
建议三击或长按进入下一话，减少点击误操作可能

**Comment by youniaogu** [comment]
已发布到 [v0.3.4](https://github.com/youniaogu/MangaReader/releases/tag/v0.3.4)

**Comment by shibuyameltdown** [comment]
> 已发布到 [v0.3.4](https://github.com/youniaogu/MangaReader/releases/tag/v0.3.4)

帅
