### ISSUE TITLE
發現會因為轉橫屏後又轉回直屏時會跳頁

### ISSUE THREAD

**Issue by Raiter123** [youniaogu/MangaReader#151]
---

**问题描述**
發現會因為轉橫屏後又轉回直屏時會多跳頁
**如何复现**
https://github.com/youniaogu/MangaReader/assets/153535038/ac3ca74d-f1a3-42fe-8e01-eb71812f9abf

**错误信息**
無

**设备信息**

Poco Phone F5 pro

**Comment by youniaogu** [comment]
已知问题，而且很难避免
