### ISSUE TITLE
增加预载图片功能，数量可选

### ISSUE THREAD

**Issue by XianYuDaXian** [youniaogu/MangaReader#152]
**现有功能改进还是新功能/插件提议？**
增加预载图片功能，预载数量可选，条漫信息量太少了，自动翻页不太实用，要么翻过头要么翻一半，类似其他阅读器。下载功能虽然可以达成，但有的时候下载速度比较慢，边下载边阅读的话经常就是下载停止了，就算退出去一会还是只能逐页加载

**请简单描述下你的需求**

**解决方案**
类似其他阅读器
![image](https://github.com/youniaogu/MangaReader/assets/20138259/b641bca4-0d4b-4591-ad86-7ff4908a9510)

**Comment by XianYuDaXian** [comment]
还有条漫的翻页方式修改为根据屏幕高度来，因为现在的一张图片一页来翻页的话会跳过很大一段。更改滑动比屏幕高度短一点的距离就好

**Comment by youniaogu** [comment]
不联系竖屏用自动翻页，那个功能是给横屏用的……
