### ISSUE TITLE
如何在自己的设备上运行这个项目

### ISSUE THREAD

**Issue by sincerely1** [youniaogu/MangaReader#157]
我是一个React Native新手，想学习如何进行开发。fork 这个项目后运行 yarn android 后可以给模拟器链接安装上软件，但启动后就会卡死在打开界面，显示一个“M”。重新加载应用后就直接显示断开链接。这个情况有人遇到过吗？
我的环境是：
- win11
- node18
- java 11
- android SDK13
环境是按照官网的配置安装的，运行样例项目没有问题。
<img width="699" alt="Code_il3RG7rRia" src="https://github.com/youniaogu/MangaReader/assets/44086696/410f350a-3f54-4d41-ac95-5773c5f119e6">

**Comment by raoxiongwen** [comment]
尝试修改一下applicationId，再启动项目，一个M是作者大佬弄的项目启动页🤣

**Comment by rucswax** [comment]
先看看有没有把 js 文件打包进去，也就是看看安装包里边有没有 bundle 文件

**Comment by sincerely1** [comment]
> 尝试修改一下applicationId，再启动项目，一个M是作者大佬弄的项目启动页🤣

我尝试删除build.gradle中的applicationId和修改为com.mangareader都不成功。难以理解为什么之后会查询不到链接的设备

**Comment by rucswax** [comment]
> > 尝试修改一下applicationId，再启动项目，一个M是作者大佬弄的项目启动页🤣
> 
> 我尝试删除build.gradle中的applicationId和修改为com.mangareader都不成功。难以理解为什么之后会查询不到链接的设备

看看安装包里有没有 bundle 文件吧，我打包了一下，发现是没有的

**Comment by sincerely1** [comment]
> > > 尝试修改一下applicationId，再启动项目，一个M是作者大佬弄的项目启动页🤣
> > 
> > 
> > 我尝试删除build.gradle中的applicationId和修改为com.mangareader都不成功。难以理解为什么之后会查询不到链接的设备
> 
> 看看安装包里有没有 bundle 文件吧，我打包了一下，发现是没有的

好的，我试一下

**Comment by sincerely1** [comment]
噶住了，build直接报错，菜鸡的我不懂native，好像和gradle的版本有关，错误提示如下：
`> Configure project :react-native-reanimated
Android gradle plugin: 7.4.2
Gradle: 8.0.1
WARNING:Software Components will not be created automatically for Maven publishing from Android Gra
dle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

The Kotlin Gradle plugin was loaded multiple times in different subprojects, which is not supported and may break the build. 
This might happen in subprojects that apply the Kotlin plugins with the Gradle 'plugins { ... }' DSL if they specify explicit versions, even if the versions are equal.
Please add the Kotlin plugin to the common parent project or the root project, then remove the versions in the subprojects.
If the parent project does not need the plugin, add 'apply false' to the plugin line.
See: https://docs.gradle.org/current/userguide/plugins.html#sec:subprojects_plugins_dsl
> Task :app:packageRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:packageRelease'.
> A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
   > SigningConfig "release" is missing required property "storeFile".

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/8.0.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 29s
653 actionable tasks: 13 executed, 640 up-to-date
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by rucswax** [comment]
> 噶住了，build直接报错，菜鸡的我不懂native，好像和gradle的版本有关，错误提示如下： `> Configure project :react-native-reanimated Android gradle plugin: 7.4.2 Gradle: 8.0.1 WARNING:Software Components will not be created automatically for Maven publishing from Android Gra dle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.
> 
> The Kotlin Gradle plugin was loaded multiple times in different subprojects, which is not supported and may break the build. This might happen in subprojects that apply the Kotlin plugins with the Gradle 'plugins { ... }' DSL if they specify explicit versions, even if the versions are equal. Please add the Kotlin plugin to the common parent project or the root project, then remove the versions in the subprojects. If the parent project does not need the plugin, add 'apply false' to the plugin line. See: https://docs.gradle.org/current/userguide/plugins.html#sec:subprojects_plugins_dsl
> 
> > Task :app:packageRelease FAILED
> 
> FAILURE: Build failed with an exception.
> 
>     * What went wrong:
>       Execution failed for task ':app:packageRelease'.
> 
> 
> > A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
> > SigningConfig "release" is missing required property "storeFile".
> 
>     * Try:
> 
> 
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> 
>     * Get more help at https://help.gradle.org
> 
> 
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
> 
> You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
> 
> See https://docs.gradle.org/8.0.1/userguide/command_line_interface.html#sec:command_line_warnings
> 
> BUILD FAILED in 29s 653 actionable tasks: 13 executed, 640 up-to-date error Command failed with exit code 1. info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> 
> 有大神能指点一下吗？

你构建 debug 版看看是不是同样的结果，我刚刚用 github action 试了，debug 版本可以正常运行

**Comment by sincerely1** [comment]
> > 噶住了，build直接报错，菜鸡的我不懂native，好像和gradle的版本有关，错误提示如下： `> Configure project :react-native-reanimated Android gradle plugin: 7.4.2 Gradle: 8.0.1 WARNING:Software Components will not be created automatically for Maven publishing from Android Gra dle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.
> > The Kotlin Gradle plugin was loaded multiple times in different subprojects, which is not supported and may break the build. This might happen in subprojects that apply the Kotlin plugins with the Gradle 'plugins { ... }' DSL if they specify explicit versions, even if the versions are equal. Please add the Kotlin plugin to the common parent project or the root project, then remove the versions in the subprojects. If the parent project does not need the plugin, add 'apply false' to the plugin line. See: https://docs.gradle.org/current/userguide/plugins.html#sec:subprojects_plugins_dsl
> > > Task :app:packageRelease FAILED
> > 
> > 
> > FAILURE: Build failed with an exception.
> > ```
> > * What went wrong:
> >   Execution failed for task ':app:packageRelease'.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > > A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
> > > SigningConfig "release" is missing required property "storeFile".
> > 
> > 
> > ```
> > * Try:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > > Run with --stacktrace option to get the stack trace.
> > > Run with --info or --debug option to get more log output.
> > > Run with --scan to get full insights.
> > 
> > 
> > ```
> > * Get more help at https://help.gradle.org
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
> > You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
> > See https://docs.gradle.org/8.0.1/userguide/command_line_interface.html#sec:command_line_warnings
> > BUILD FAILED in 29s 653 actionable tasks: 13 executed, 640 up-to-date error Command failed with exit code 1. info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> > 有大神能指点一下吗？
> 
> 你构建 debug 版看看是不是同样的结果，我刚刚用 github action 试了，debug 版本可以正常运行

G，debug版本可以打包，但还是卡在“M” 字母这里，之后就会无响应 〒▽〒

**Comment by rucswax** [comment]
> > > 噶住了，build直接报错，菜鸡的我不懂native，好像和gradle的版本有关，错误提示如下： `> Configure project :react-native-reanimated Android gradle plugin: 7.4.2 Gradle: 8.0.1 WARNING:Software Components will not be created automatically for Maven publishing from Android Gra dle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.
> > > The Kotlin Gradle plugin was loaded multiple times in different subprojects, which is not supported and may break the build. This might happen in subprojects that apply the Kotlin plugins with the Gradle 'plugins { ... }' DSL if they specify explicit versions, even if the versions are equal. Please add the Kotlin plugin to the common parent project or the root project, then remove the versions in the subprojects. If the parent project does not need the plugin, add 'apply false' to the plugin line. See: https://docs.gradle.org/current/userguide/plugins.html#sec:subprojects_plugins_dsl
> > > > Task :app:packageRelease FAILED
> > > 
> > > 
> > > FAILURE: Build failed with an exception.
> > > ```
> > > * What went wrong:
> > >   Execution failed for task ':app:packageRelease'.
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > > A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
> > > > SigningConfig "release" is missing required property "storeFile".
> > > 
> > > 
> > > ```
> > > * Try:
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > > Run with --stacktrace option to get the stack trace.
> > > > Run with --info or --debug option to get more log output.
> > > > Run with --scan to get full insights.
> > > 
> > > 
> > > ```
> > > * Get more help at https://help.gradle.org
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
> > > You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
> > > See https://docs.gradle.org/8.0.1/userguide/command_line_interface.html#sec:command_line_warnings
> > > BUILD FAILED in 29s 653 actionable tasks: 13 executed, 640 up-to-date error Command failed with exit code 1. info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> > > 有大神能指点一下吗？
> > 
> > 
> > 你构建 debug 版看看是不是同样的结果，我刚刚用 github action 试了，debug 版本可以正常运行
> 
> G，debug版本可以打包，但还是卡在“M” 字母这里，之后就会无响应 〒▽〒

debug 能打包说明是签名问题，相关代码链接应该是[https://github.com/youniaogu/MangaReader/blob/6434ebe1dabb28aec53c4b88f58f3ea7a052d5f1/android/app/build.gradle#L91](https://github.com/youniaogu/MangaReader/blob/6434ebe1dabb28aec53c4b88f58f3ea7a052d5f1/android/app/build.gradle#L91)

打不开软件，可能是 js 文件没打包进程序，所以，要先在根目录执行（以 linux 为例）
```shell
# 创建 assets 目录
mkdir android/app/src/main/assets
# 将 js 文件打包成 bundle 文件
npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/
```
再编译程序

**Comment by sincerely1** [comment]
> > > > 噶住了，build直接报错，菜鸡的我不懂native，好像和gradle的版本有关，错误提示如下： `> Configure project :react-native-reanimated Android gradle plugin: 7.4.2 Gradle: 8.0.1 WARNING:Software Components will not be created automatically for Maven publishing from Android Gra dle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.
> > > > The Kotlin Gradle plugin was loaded multiple times in different subprojects, which is not supported and may break the build. This might happen in subprojects that apply the Kotlin plugins with the Gradle 'plugins { ... }' DSL if they specify explicit versions, even if the versions are equal. Please add the Kotlin plugin to the common parent project or the root project, then remove the versions in the subprojects. If the parent project does not need the plugin, add 'apply false' to the plugin line. See: https://docs.gradle.org/current/userguide/plugins.html#sec:subprojects_plugins_dsl
> > > > > Task :app:packageRelease FAILED
> > > > 
> > > > 
> > > > FAILURE: Build failed with an exception.
> > > > ```
> > > > * What went wrong:
> > > >   Execution failed for task ':app:packageRelease'.
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > > A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
> > > > > SigningConfig "release" is missing required property "storeFile".
> > > > 
> > > > 
> > > > ```
> > > > * Try:
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > > Run with --stacktrace option to get the stack trace.
> > > > > Run with --info or --debug option to get more log output.
> > > > > Run with --scan to get full insights.
> > > > 
> > > > 
> > > > ```
> > > > * Get more help at https://help.gradle.org
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
> > > > You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
> > > > See https://docs.gradle.org/8.0.1/userguide/command_line_interface.html#sec:command_line_warnings
> > > > BUILD FAILED in 29s 653 actionable tasks: 13 executed, 640 up-to-date error Command failed with exit code 1. info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> > > > 有大神能指点一下吗？
> > > 
> > > 
> > > 你构建 debug 版看看是不是同样的结果，我刚刚用 github action 试了，debug 版本可以正常运行
> > 
> > 
> > G，debug版本可以打包，但还是卡在“M” 字母这里，之后就会无响应 〒▽〒
> 
> debug 能打包说明是签名问题，相关代码链接应该是
> 
> https://github.com/youniaogu/MangaReader/blob/6434ebe1dabb28aec53c4b88f58f3ea7a052d5f1/android/app/build.gradle#L91-L99
> 
> 打不开软件，可能是 js 文件没打包进程序，所以，要先在根目录执行（以 linux 为例）
> 
> ```shell
> # 创建 assets 目录
> mkdir android/app/src/main/assets
> # 将 js 文件打包成 bundle 文件
> npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/
> ```
> 
> 再编译程序

感谢大佬，终于打包的debug能进入应用了～(￣▽￣～)(～￣▽￣)～

**Comment by sincerely1** [comment]
有大神能加一下，怎样调试吗？上面大神的方法能打包，但不方便调试看修改结果，感觉好难呀，半天查不到一点资料(＞﹏＜)
