### ISSUE TITLE
话说能加点生肉图源吗

### ISSUE THREAD

**Issue by shibuyameltdown** [youniaogu/MangaReader#16]
像是mangaraw[](https://mangaraw.ru/) 
klmag之类的https://klmanga.net/mainn
谢谢叠🙇

**Comment by youniaogu** [comment]
可以加但没那么快，目前在写备份恢复功能，新图源得等下下个更新

**Comment by shibuyameltdown** [comment]
好的好的

**Comment by sakurrasama** [comment]
bika也一起加

**Comment by youniaogu** [comment]
@shibuyameltdown [v0.3.5](https://github.com/youniaogu/MangaReader/releases/tag/v0.3.5)增加了KL漫画

**Comment by youniaogu** [comment]
@sakurrasama bika内容需要登录才能访问，我不想接入账号之类的功能，非常抱歉

**Comment by shibuyameltdown** [comment]
> @shibuyameltdown [v0.3.5](https://github.com/youniaogu/MangaReader/releases/tag/v0.3.5)增加了KL漫画

好好好，谢谢叠😚
