### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by linsui** [youniaogu/MangaReader#18]
请问我可以将这个应用打包提交到 F-Droid 吗？

**Comment by linsui** [comment]
vision-camera-code-scanner 这个库用了 mlkit，mlkit 不开源，我会把这个库 patch 掉，可以吗？

**Comment by youniaogu** [comment]
你fork后自行修改打包就好啦，这个项目是[MIT](https://github.com/youniaogu/MangaReader/blob/master/LICENSE) License的

**Comment by linsui** [comment]
fork 之后我很难跟踪上游更新。我看看我能不能添加个 flavor 使用开源的库。

**Comment by youniaogu** [comment]
git可以拉上游仓库代码，只是会有合并冲突，因为你本地有变更

没问题的话，我先close了

**Comment by linsui** [comment]
好的
