### ISSUE TITLE
希望能显示tag

### ISSUE THREAD

**Issue by STSnaive** [youniaogu/MangaReader#19]
首先感谢作者的制作，app界面简洁，操作直观，已star。
有一个小建议，像jmcomic这种源，如果可以显示tag，并且能点击tag和作者名进行搜索就更加实用了。

**Comment by youniaogu** [comment]
tag内容有存，但只能把他们作为关键字进行搜索，反应到筛选条件上会比较难

**Comment by youniaogu** [comment]
[v0.3.5](https://github.com/youniaogu/MangaReader/releases/tag/v0.3.5) 上已实现
