### ISSUE TITLE
强烈推荐漫画猫 很全

### ISSUE THREAD

**Issue by JONREAN2** [youniaogu/MangaReader#2]
https://www.maofly.com/

**Comment by JONREAN2** [comment]
> https://www.maofly.com/

希望可以加上

**Comment by youniaogu** [comment]
@JONREAN2 非常感谢你的建议，目前正在开发禁漫天堂，完成后会加入漫画猫

**Comment by JONREAN2** [comment]
> @JONREAN2 非常感谢你的建议，目前正在开发禁漫天堂，完成后会加入漫画猫

感谢

**Comment by youniaogu** [comment]
已发布 [v0.2.2](https://github.com/youniaogu/MangaReader/releases/tag/v0.2.2)

**Comment by JONREAN2** [comment]
> 

nb
