### ISSUE TITLE
建议增加几个源，和支持 ipad OS

### ISSUE THREAD

**Issue by Grouppppp** [youniaogu/MangaReader#20]
源仓库中有一些源，是适配的异次元app，请问可否修改为适配本app呢？源地址：https://www.yckceo.com/yiciyuan/tuyuan/index.html
另外我在 ipad 上装上 ipa 后发现是手机版本，请问打包时可否打包为通用版本，适配更大的屏幕？

**Comment by youniaogu** [comment]
@Grouppppp 抱歉，目前做完nhentai插件后暂时不会加其他的源，因为多了维护成本比较高

然后ipad的问题，可能是因为我没有勾上这个，等下个版本更新就可以了
![截屏2023-02-13 10 00 39](https://user-images.githubusercontent.com/13073995/218354125-7db0f6dc-902c-4e73-be76-00d84d4f886a.png)
