### ISSUE TITLE
希望话数的顺序调换一下和增加下载

### ISSUE THREAD

**Issue by yuduotianguang** [youniaogu/MangaReader#21]

**Comment by yuduotianguang** [comment]
漫画柜mobile的漫画寄了希望修一下

**Comment by youniaogu** [comment]
有报错截图吗

**Comment by yuduotianguang** [comment]
> 有报错截图吗

![-3cbe89643661da4a.jpg](https://user-images.githubusercontent.com/104707441/220023087-d3bc4ca2-e66a-4481-b356-8db791d52fa5.jpg)

**Comment by youniaogu** [comment]
@yuduotianguang 抱歉，没有复现出来，建议检查下代理（漫画柜屏蔽日本ip），然后试下浏览器能不能打开https://m.manhuagui.com

**Comment by yuduotianguang** [comment]
> @yuduotianguang 抱歉，没有复现出来，建议检查下代理（漫画柜屏蔽日本ip），然后试下浏览器能不能打开https://m.manhuagui.com

用的香港IP，网页打得开，就APP打不开，APP其他几个都可以打开

**Comment by youniaogu** [comment]
> > @yuduotianguang 抱歉，没有复现出来，建议检查下代理（漫画柜屏蔽日本ip），然后试下浏览器能不能打开https://m.manhuagui.com
> 
> 用的香港IP，网页打得开，就APP打不开，APP其他几个都可以打开

我没有香港ip的代理，你可以帮我调试下吗

浏览器或postman打开[https://m.manhuagui.com/list/?page=1&catid=0&ajax=1&order=](https://m.manhuagui.com/list/?page=1&catid=0&ajax=1&order=)，然后把这个地址的response复制给我就好了

**Comment by yuduotianguang** [comment]
> > > @yuduotianguang 抱歉，没有复现出来，建议检查下代理（漫画柜屏蔽日本ip），然后试下浏览器能不能打开https://m.manhuagui.com
> > 
> > 用的香港IP，网页打得开，就APP打不开，APP其他几个都可以打开
> 
> 我没有香港ip的代理，你可以帮我调试下吗
> 
> 浏览器或postman打开[https://m.manhuagui.com/list/?page=1&catid=0&ajax=1&order=](https://m.manhuagui.com/list/?page=1&catid=0&ajax=1&order=)，然后把这个地址的response复制给我就好了
> 

![-1afab385520ea80f.jpg](https://user-images.githubusercontent.com/104707441/220128886-54018318-5f27-4e6c-ba7d-ec549942e855.jpg)![-44cf596836b6b36e.jpg](https://user-images.githubusercontent.com/104707441/220128914-1466a73d-e525-400d-8390-991a16cceb37.jpg)现在封面倒是有了，却显示这个

**Comment by youniaogu** [comment]
@yuduotianguang 看第一张图response是对的，第二张报错是因为网络问题导致，可能你的代理不太稳定

**Comment by youniaogu** [comment]
[v0.4.1](https://github.com/youniaogu/MangaReader/releases/tag/v0.4.1)
