### ISSUE TITLE
希望可以加一个从右往左的阅读方式选项

### ISSUE THREAD

**Issue by yuyuyuc** [youniaogu/MangaReader#23]
感谢大佬

**Comment by youniaogu** [comment]
这个功能已经有了，在这里
<img src="https://user-images.githubusercontent.com/13073995/227451975-29eed452-e55a-4963-ba35-07acffd42827.jpg" width="250" />

**Comment by youniaogu** [comment]
有其他问题也欢迎issues

**Comment by yuyuyuc** [comment]
> 有其他问题也欢迎issues

感谢大佬，居然一直没发现^_^
