### ISSUE TITLE
跳转下一话

### ISSUE THREAD

**Issue by LiuGengYang** [youniaogu/MangaReader#24]
现在看完当前话只能点击切换下一话 希望增加自动跳转功能  漫画详情页也可以加一个继续阅读的按钮 不然每次都要自己点话数

**Comment by youniaogu** [comment]
谢谢反馈，我会尝试做一个无限翻页的功能，这样就不需要点下一话了

**Comment by youniaogu** [comment]
已实现 [v0.4.2](https://github.com/youniaogu/MangaReader/releases/tag/v0.4.2)
