### ISSUE TITLE
拷贝漫画单行本缺失

### ISSUE THREAD

**Issue by kaixue233** [youniaogu/MangaReader#25]
https://copymanga.site/h5/details/comic/xiansannongjiadeluanmajineng
比如这本漫画分为默认和单行本，单行本的版本看不了。
![44E94346-4E68-4D49-A005-89095BB2D62D](https://user-images.githubusercontent.com/20300292/229342140-5ec24922-cd4d-4b1e-bcd0-321a4ca47c81.jpeg)
![E5EEF556-FC01-447B-A52F-BE80D5DD20D8](https://user-images.githubusercontent.com/20300292/229342146-08a649c8-f956-4407-86a9-8594e3bbfa5c.jpeg)

**Comment by youniaogu** [comment]
下次更新会修复

**Comment by youniaogu** [comment]
fixed [v0.5.0](https://github.com/youniaogu/MangaReader/releases/tag/v0.5.0)
