### ISSUE TITLE
请问可以修改下载路径吗？

### ISSUE THREAD

**Issue by rusthx** [youniaogu/MangaReader#27]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by youniaogu** [comment]
下次更新我会加上

**Comment by youniaogu** [comment]
fixed [v0.5.0](https://github.com/youniaogu/MangaReader/releases/tag/v0.5.0)
