### ISSUE TITLE
横屏的时候希望可以自适应缩放图片并同时显示两页，还有墨水屏的适配

### ISSUE THREAD

**Issue by XianYuDaXian** [youniaogu/MangaReader#28]
作者你好又是我，现在买了个墨水屏平板来看漫画，发现横屏后图片会保持竖屏的比例导致超出平板显示大小，希望可以像B漫水墨屏版一样，竖屏正常显示，横屏可以双页，然后用音量键翻页。还有能不能适配墨水屏呢？开启墨水屏后去掉所有动画减少闪烁。谢谢
![208B18F1D6C54AB933F876F870207726](https://user-images.githubusercontent.com/20138259/233790246-d59b8204-cff4-49ba-b8a8-d3fae192b2c7.jpg)

**Comment by youniaogu** [comment]
抱歉我没有水墨屏设备，所以没办法做适配还有测试，或者你能说下具体要修改的点吗

然后是`横屏超出平板显示大小`的问题，你可以试试先切换至横屏再进入app，就会以横屏宽度去计算。这个问题是因为`app没有做横竖屏响应`，并且`锁定了竖屏`

关于单双页，等有空时我会去看下

**Comment by XianYuDaXian** [comment]
好的谢谢作者，按照我这几天的墨水屏使用来看，适配墨水屏应该注意几点就很好了。
1.app的所有过渡动画，点击，滑动都去掉，减少闪烁，比如说加载动画用静态icon代替。
2.app配色色系尽量浅色，对比不要太大，不然刷新有残留。比如说白色文字title黑色底栏，这样一刷新就会有文字的浅浅残留。还有阅读背景用白色不是黑色也是同样理由。
3.翻页可以用点击翻页和音量键翻页代替，滑动翻页有残留。

**Comment by XianYuDaXian** [comment]
还有作者，我发现安卓上漫画柜的源网络报错，但是同一网络下的iOS设备就可以正常显示，希望可以修复
![Screenshot_2023-05-04-21-34-03-23_7d078d92158a72d0acb8d0aa780f3681](https://user-images.githubusercontent.com/20138259/236223389-f716ea9c-1f7a-4e11-9cc0-4c6d35989bdd.jpg)
![IMG_0219 (2)](https://user-images.githubusercontent.com/20138259/236223430-135b1243-d2d5-482f-85c5-a66d7a779466.JPG)

**Comment by youniaogu** [comment]
@XianYuDaXian 你的安卓设备没有挂代理吧

**Comment by XianYuDaXian** [comment]
> @XianYuDaXian 你的安卓设备没有挂代理吧

我是路由器科学上网的，所有设备都是同一个网络的。但是安卓设备哪怕是开4G然后单独开clash也是一样报错，网页版漫画柜是正常看的

**Comment by youniaogu** [comment]
我安卓机不在身边，暂时没法测试，只能你先看下

如果你的代理用gfwlist自动匹配的话，可以检查下[m.manhuagui.com](m.manhuagui.com)这个域名是否匹配规则
<img src="https://user-images.githubusercontent.com/13073995/236366411-77523c78-e629-4db5-a1f2-78fc8215f42a.jpg" width="300" />

也可以在Plugins页面里看下webview能否打开
<img src="https://user-images.githubusercontent.com/13073995/236367205-17b691bd-f662-4d8c-bcdc-51d437345b33.jpg" width="300" />

**Comment by XianYuDaXian** [comment]
> 我安卓机不在身边，暂时没法测试，只能你先看下
> 
> 如果你的代理用gfwlist自动匹配的话，可以检查下[m.manhuagui.com](m.manhuagui.com)这个域名是否匹配规则 <img alt="" width="300" src="https://user-images.githubusercontent.com/13073995/236366411-77523c78-e629-4db5-a1f2-78fc8215f42a.jpg">
> 
> 也可以在Plugins页面里看下webview能否打开 <img alt="" width="300" src="https://user-images.githubusercontent.com/13073995/236367205-17b691bd-f662-4d8c-bcdc-51d437345b33.jpg">

我路由器的规则代理已经手动添加上了 然后安卓上单独开的是全局代理还是不行 不过试了一下那个webiew倒是可以正常打开网页 
![Screenshot_20230505_104705_com mangareader](https://user-imag
![Screenshot_20230505_104956_com huawei android launcher](https://user-images.githubusercontent.com/20138259/236368527-8c041614-9e17-4063-98b2-15152a7a295c.jpg)
es.githubusercontent.com/20138259/236368517-34c0d59c-ef8c-4ebe-adec-2abd1148bffb.jpg)

**Comment by youniaogu** [comment]
那有可能是header头的原因

能帮我试下Discovery页和Search页有没有问题吗（`大概率Discovery正常，Search会报错`）

**Comment by XianYuDaXian** [comment]
> 那有可能是header头的原因
> 
> 能帮我试下Discovery页和Search页有没有问题吗（`大概率Discovery正常，Search会报错`）

都是正常的，无论是首页下滑更多还是切换分类排序，还有搜索页都能正常显示，就是进入具体漫画会报网络错误。

**Comment by youniaogu** [comment]
我的安卓机没有复现，但我发现MHGM详情页有个301跳转的问题，你可以试下[v0.5.1](https://github.com/youniaogu/MangaReader/releases/tag/v0.5.1)

<img width="300" alt="image" src="https://user-images.githubusercontent.com/13073995/236682619-b95f753e-b363-41d2-af00-e55c10c29db2.png">

**Comment by XianYuDaXian** [comment]
> 我的安卓机没有复现，但我发现MHGM详情页有个301跳转的问题，你可以试下[v0.5.1](https://github.com/youniaogu/MangaReader/releases/tag/v0.5.1)
> 
> <img alt="image" width="300" src="https://user-images.githubusercontent.com/13073995/236682619-b95f753e-b363-41d2-af00-e55c10c29db2.png">
好的，试了下正常了。那作者有时间能做下墨水屏的适配吗？或者先加上白色加载背景和音量键翻页也行。谢谢

**Comment by youniaogu** [comment]
有空的话我会去看

**Comment by XianYuDaXian** [comment]
作者，我又发现一个bug，有些被列为版权限制或者成年限制的漫画，直接搜索是搜不到的，哪怕是网页上搜索也没有，只有网站那个联想搜索能搜出来，点进去后点击继续阅读就可以看了。app有办法也能看吗？

**Comment by XianYuDaXian** [comment]
作者，我又发现一个bug，有些被列为版权限制或者成年限制的漫画，直接搜索是搜不到的，哪怕是网页上搜索也没有，只有网站那个联想搜索能搜出来，点进去后点击继续阅读就可以看了。app有办法也能看吗？
![2E884E37-22ED-452B-A377-0716A5C23B57](https://user-images.githubusercontent.com/20138259/236976185-873bb194-d57b-40d8-b8f7-04a0cf9ebdc6.jpeg)
![8E2C1E74-B5D0-4FF0-A96E-D6859F8D7FE9](https://user-images.githubusercontent.com/20138259/236976191-d4f8aa2d-1d1b-4b60-94c2-0e68c0c38b62.jpeg)

**Comment by youniaogu** [comment]
> 作者，我又发现一个bug，有些被列为版权限制或者成年限制的漫画，直接搜索是搜不到的，哪怕是网页上搜索也没有，只有网站那个联想搜索能搜出来，点进去后点击继续阅读就可以看了。app有办法也能看吗？ ![2E884E37-22ED-452B-A377-0716A5C23B57](https://user-images.githubusercontent.com/20138259/236976185-873bb194-d57b-40d8-b8f7-04a0cf9ebdc6.jpeg) ![8E2C1E74-B5D0-4FF0-A96E-D6859F8D7FE9](https://user-images.githubusercontent.com/20138259/236976191-d4f8aa2d-1d1b-4b60-94c2-0e68c0c38b62.jpeg)

app里搜的到也可以看（下次遇到不同的问题最好开个新的issues，这样比较好管理，其他人搜的时候也方便）

**Comment by SilenceXK** [comment]
没几个牛逼的图源了（大悲）

**Comment by youniaogu** [comment]
更新一下

+ 墨水屏原本打算用主题切换去实现的，但彩图、动图缺少Filter属性没法实现，只能pass掉
+ 单双页需求修改地方太多，时间有限也pass了
+ 音量键翻页已实现（0或满音量时会切换到0.1/0.9音量去适配），下版本更新
+ 旋转适配已实现，漫画阅读的时候因为flashlist有bug([781](https://github.com/Shopify/flash-list/issues/781)、[581](https://github.com/Shopify/flash-list/issues/581))，旋转后会出现截断，返回重进就可以了，下版本更新

**Comment by youniaogu** [comment]
[v0.5.2](https://github.com/youniaogu/MangaReader/releases/tag/v0.5.2) 已更新
