### ISSUE TITLE
希望添加自动旋转屏幕（重力感应）功能

### ISSUE THREAD

**Issue by VCE1** [youniaogu/MangaReader#29]
因为有时候使用到有线耳机或充电线，体验不是很好。

**Comment by youniaogu** [comment]
不是很没理解你的意思，能具体说下使用有线耳机或充电线会影响到什么吗

**Comment by VCE1** [comment]
抱歉没说清楚，因为我自己使用的ipad，一般是不会用手托着设备而是靠在支起来的腿上，所以当设备竖屏的时候充电口就会朝下而没法充电了，有线耳机也要使用c口同理。如果能够自动旋转倒转过来，让充电口朝上就能解决这个问题了。

**Comment by youniaogu** [comment]
@VCE1 APP有做自适应，但没有做横竖屏响应，并且锁定竖屏

关于你的问题，可以放开竖屏锁定，但切换横竖屏时需要重新打开APP，不然布局会出现问题

举个例子：`设备竖屏状态下打开APP，然后把设备从竖屏转到横屏，页面并不会以横屏宽度重新渲染`

**Comment by youniaogu** [comment]
下次更新会放开竖屏锁定，横竖屏响应等后面有空的时候再看

**Comment by VCE1** [comment]
ok，辛苦大佬了

**Comment by youniaogu** [comment]
fixed [v0.5.0](https://github.com/youniaogu/MangaReader/releases/tag/v0.5.0)
