### ISSUE TITLE
更新后，在下载漫画时显示创建文件夹失败？请问怎么解决呢？

### ISSUE THREAD

**Issue by rusthx** [youniaogu/MangaReader#30]
![Screenshot_20230427_154923](https://user-images.githubusercontent.com/125135983/234853838-3446c44e-9c8f-4a25-bf5a-7f60fbbab73c.jpg)

**Comment by youniaogu** [comment]
可以看下你设置的路径吗

**Comment by rusthx** [comment]
额 抱歉 我不知道怎么设置下载路径

**Comment by rusthx** [comment]
在About那里 无法修改下载路径

**Comment by youniaogu** [comment]
<img width="240" alt="截屏2023-04-27 20 26 25" src="https://user-images.githubusercontent.com/13073995/234861619-787a5169-2d0c-409b-8342-e06613d0e056.png">
这里不能修改吗，是无法输入还是什么问题？

**Comment by rusthx** [comment]
点击没有反应，长按也不行

**Comment by youniaogu** [comment]
@rusthx 你用的什么设备，安卓几？我看模拟器能不能复现一下

**Comment by rusthx** [comment]
我用别人的手机试了一下（红米note 10)， 可以正常修改路径;然后我又卸载重装了一下，还是不能修改下载路径（甚至下载都会报错无法创建文件夹）
![Screenshot_20230430_105247](https://user-images.githubusercontent.com/125135983/235333318-e532f71d-d57d-4bfa-a25b-7dc841f31e01.jpg)

**Comment by youniaogu** [comment]
@rusthx 

模拟器没能复现，但看你的截图，似乎是[RNFS](https://github.com/alpha0010/react-native-file-access)的`Dirs.SDCardDir`返回数据错误（返回了三个storage，sdcard、usb1、usb2？），理论上应该是`/storage/sdcard`或者`/sdcard`

我会去RNFS那边看一下，有发现的话我会同步在这里

**Comment by youniaogu** [comment]
现在 [v0.5.1](https://github.com/youniaogu/MangaReader/releases/tag/v0.5.1) 可以修改整个下载目录

你可以试着修改为`/storage/sdcard/{path}/{chapter}`或`/sdcard/{path}/{chapter}`

**Comment by rusthx** [comment]
已经可以修改了，非常感谢
