### ISSUE TITLE
无法加载漫画，但是可以搜索漫画

### ISSUE THREAD

**Issue by yuyuyuc** [youniaogu/MangaReader#32]
![Screenshot_2023-05-03-21-53-48-663_com.mangareader.jpg](https://user-images.githubusercontent.com/128778890/235936817-d4e4639d-d6d1-401c-acce-62b7537ad2f3.jpg)

**Comment by yuyuyuc** [comment]
开了vpn可以看，现在不能直连吗

**Comment by youniaogu** [comment]
![截屏2023-05-04 10 14 43](https://user-images.githubusercontent.com/13073995/236096516-4005686f-c946-43ec-82ae-271e5433d84e.png)

是的，晚点我会换成这个地址

**Comment by yuyuyuc** [comment]
好的👌

**Comment by youniaogu** [comment]
@yuyuyuc 似乎[copymanga.site](https://copymanga.site/)这个地址恢复了，你再试下

**Comment by yuyuyuc** [comment]
@youniaogu 还是连不上

**Comment by youniaogu** [comment]
[v0.5.1](https://github.com/youniaogu/MangaReader/releases/tag/v0.5.1) 已经将域名修改为[copymanga.tv](https://www.copymanga.tv/)
