### ISSUE TITLE
频繁出现json的报错

### ISSUE THREAD

**Issue by shibuyameltdown** [youniaogu/MangaReader#33]
0.50版本，拷贝源。试了直连，配置，全局，都会出现。
![IMG_2116](https://user-images.githubusercontent.com/78797438/236361271-72f53f42-cea0-4926-85c7-23366b51065e.png)

**Comment by youniaogu** [comment]
刚试了下，没复现出来
<img src="https://user-images.githubusercontent.com/13073995/236365185-cea21837-e508-4830-9c62-f37e6f74c83e.jpg" width="300" />
你点这里用浏览器打开，看下是不是网络的问题

**Comment by shibuyameltdown** [comment]
![IMG_2117](https://user-images.githubusercontent.com/78797438/236368194-3fce3dd1-f1c1-49fa-8a51-dc5e3fce09ae.png)

**Comment by youniaogu** [comment]
[v0.5.1](https://github.com/youniaogu/MangaReader/releases/tag/v0.5.1) 修改了拷贝漫画域名

**Comment by shibuyameltdown** [comment]
> [v0.5.1](https://github.com/youniaogu/MangaReader/releases/tag/v0.5.1) 修改了拷贝漫画域名

支持
