### ISSUE TITLE
切换nh显示cookie错误是什么情况

### ISSUE THREAD

**Issue by linyu7253** [youniaogu/MangaReader#36]

**Comment by youniaogu** [comment]
[readme](https://github.com/youniaogu/MangaReader#nhentai)上有说

**Comment by linyu7253** [comment]
可它有时候会显示错误啊，我就是按照你的方法去弄的

**Comment by youniaogu** [comment]
> 可它有时候会显示错误啊，我就是按照你的方法去弄的

cookies有过期时间，切换代理也会导致cookies失效，重新去webview里再获取就好了

**Comment by linyu7253** [comment]
webview是什么（我是个萌新不太懂）

**Comment by linyu7253** [comment]
![Screenshot_2023-05-15-11-35-12-757_com mangareader](https://github.com/youniaogu/MangaReader/assets/133612787/9425f27e-ef01-47ae-9f9e-74e72da8adbe)
又不行了

**Comment by youniaogu** [comment]
按readme上的流程重新获取就行了，还有确认android版本是不是大于9

**Comment by linyu7253** [comment]
我安卓12

**Comment by youniaogu** [comment]
你先重新打开app，然后按[readme](https://github.com/youniaogu/MangaReader#nhentai)的流程获取cookie，同时确认webviw里能不能正常访问nhentai（通过cloudflare验证，正确打开网站并且图片显示正常），再回去重新请求（点中间的ame动图或者重新选择nh插件都可以）

然后cookie不是一直有效的，超时（理论上不会，时间很久的）或者网络环境改变都会导致失效无法通过cloudflare验证，这时按上面流程重新走一遍就行了
