### ISSUE TITLE
大佬，安卓机其他网站打开都没问题，jmc列表夜没问题，但是点进漫画里却没有任何话数，都是空白，每一篇漫画都是如此。

### ISSUE THREAD

**Issue by claryxu** [youniaogu/MangaReader#37]
**注意**

- 提问前请检索相关 issues，避免重复提问
- 如遇到无法使用或无法加载的情况，请先去浏览器或 webview 里访问原网站排除网络问题
- 请按照 issues 模板提供相关信息
- 请尽可能把多的信息吐出来，避免挤牙膏

---

**问题描述**

**如何复现**

**错误信息**

**设备信息**

**Comment by claryxu** [comment]
![image](https://github.com/youniaogu/MangaReader/assets/132184423/5d692706-2098-41df-9ff6-3bc490a91972)

**Comment by youniaogu** [comment]
已修复，下个版本更新

**Comment by youniaogu** [comment]
[v0.5.2](https://github.com/youniaogu/MangaReader/releases/tag/v0.5.2) 已更新
