### ISSUE TITLE
能否预加载下一话内容

### ISSUE THREAD

**Issue by shibuyameltdown** [youniaogu/MangaReader#38]
rt，翻到下一话的时候也感觉不太连贯

**Comment by youniaogu** [comment]
已经有了，在 [v0.4.2](https://github.com/youniaogu/MangaReader/releases/tag/v0.4.2) 第二条

**Comment by shibuyameltdown** [comment]
但是感觉实际体验不是很好，切下一话的时候总会加载一下，就算第一页没加载第二第三页也会加载_(:з」∠)_

**Comment by youniaogu** [comment]
“切下一话的时候总会加载一下”，不是很理解，有截图或者视频说明下吗（还有提issues请按照模版填写，节省大家时间）

**Comment by shibuyameltdown** [comment]
好的，下次一定。现在设备不在手边，中午才有录屏

**Comment by shibuyameltdown** [comment]
无法复现了，感觉可能是网太慢或者拷贝响应太慢的原因，现在正常翻页也要加载😰
