### ISSUE TITLE
切屏会出现显示错误

### ISSUE THREAD

**Issue by shibuyameltdown** [youniaogu/MangaReader#39]
https://streamja.com/ybBLm
见视频

实测只要切屏（切回桌面或者其他app）都会出现

设备是ipad mini4，系统ios15.7

**Comment by youniaogu** [comment]
已复现，但还没定位到问题（欢迎PR）

**Comment by youniaogu** [comment]
升级react-native框架后问题没有复现过了，具体可以看[v0.6.0-rc.2](https://github.com/youniaogu/MangaReader/releases/tag/v0.6.0-rc.2)
