### ISSUE TITLE
大佬在readme.md 演示文件中 哪个是ios的吧，请问可以把这个ipa分享一下嘛

### ISSUE THREAD

**Issue by JONREAN2** [youniaogu/MangaReader#4]
最好是最新版本的 非常感谢
上次我打包了一下，打开一直404

**Comment by youniaogu** [comment]
@JONREAN2  没有开发者账号，打不了ipa包，sorry
还有你说的404是指什么

**Comment by JONREAN2** [comment]
> @JONREAN2 没有开发者账号，打不了ipa包，sorry 还有你说的404是指什么

那为啥演示哪个动画是iOS的阿，你是怎么安装的呀，我朋友有开发者账号 他打包了一下 我们进去软件没用网络 ，界面显示404

**Comment by youniaogu** [comment]
@JONREAN2 xcode可以免费签名，有效期7天。主界面404的话意思是没有收藏漫画，可以去上面搜索添加

**Comment by JONREAN2** [comment]
> @JONREAN2 xcode可以免费签名，有效期7天。主界面404的话意思是没有收藏漫画，可以去上面搜索添加

收到 我试一试

**Comment by JONREAN2** [comment]
> @JONREAN2 xcode可以免费签名，有效期7天。主界面404的话意思是没有收藏漫画，可以去上面搜索添加

已经按照好了 使用感受还行 尤其加载动画 但功能还是太少 
1 增加观看记忆功能 下次打开能从上次停留的直接观看
2 加载时间较长 能有预加载就好了 
3 增加竖屏显示 （非常需要
![07740ec99ce786ac2b071c58a7df87d](https://user-images.githubusercontent.com/86515969/185835092-47db61d8-be85-44d9-9005-a5b0f4b145eb.jpg)
![116d25e3344574bdda9b4d18af13d5f](https://user-images.githubusercontent.com/86515969/185835214-545ee61b-e9fe-49cc-b114-46f055c573d6.png)
4 ui 可以这样调整丰富一下 首页感觉最好是可以选择漫话是界面？  
![9a0512c60d8917001c291ded112d21a](https://user-images.githubusercontent.com/86515969/185836299-c75fc8e3-d210-4fc2-a7d2-07ae3f3cdd54.jpg)
5 增加升级功能
