### ISSUE TITLE
音量键翻页翻了几页就没响应

### ISSUE THREAD

**Issue by XianYuDaXian** [youniaogu/MangaReader#40]
**注意**

- 提问前请检索相关 issues，避免重复提问
- 如遇到无法使用或无法加载的情况，请先去浏览器或 webview 里访问原网站排除网络问题
- 请按照 issues 模板提供相关信息
- 请尽可能把多的信息吐出来，避免挤牙膏

---

**问题描述**

**如何复现**

音量键翻页时不时失效，下一页已经加载出来了，但是无法音量键翻页，只能滑动。而且音量键翻页不能到下一话或者上一话，滑动是可以的。我以前是用遥控器左右滑动切换，现在更新音量键翻页后，对于遥控的左右键也不响应了。我录了个视频可以看下。还有就是漫画加载页面能不能用白底？黑底的话水墨屏会有印记。或者能够自由切换加载的背景色就好了

**错误信息**

音量键翻页时不时失效

**设备信息**
联想小新pad pro 2021
华为matepad paper
安卓12

https://github.com/youniaogu/MangaReader/assets/20138259/2bd05f39-84e7-4e8e-9d6c-012fc6d0cd51

**Comment by youniaogu** [comment]
谢谢反馈，复现了，在想办法解决

白底我会在阅读页面增加一个切换按钮，跟横竖屏、左右阅读切换类似的

**Comment by youniaogu** [comment]
[v0.5.3](https://github.com/youniaogu/MangaReader/releases/tag/v0.5.3) 已修复
