### ISSUE TITLE
音量键翻页还是有bug，大概5页就会翻不动

### ISSUE THREAD

**Issue by XianYuDaXian** [youniaogu/MangaReader#41]
**注意**

- 提问前请检索相关 issues，避免重复提问
- 如遇到无法使用或无法加载的情况，请先去浏览器或 webview 里访问原网站排除网络问题
- 请按照 issues 模板提供相关信息
- 请尽可能把多的信息吐出来，避免挤牙膏

---

**问题描述**

**如何复现**

音量键翻页还是有bug，大概翻5页就会翻不动,滑动翻页倒是可以。

**错误信息**

[](https://github.com/youniaogu/MangaReader/assets/20138259/49819048-cc4a-4c1a-ae8f-f3b0f44ea6d3)

**设备信息**

联想小新pad pro 2021 华为matepad paper 安卓12

**Comment by youniaogu** [comment]
@XianYuDaXian 可以试下 [v0.5.4](https://github.com/youniaogu/MangaReader/releases/tag/v0.5.4)

翻不动是因为翻页后有概率page不会更新（android下会有这个问题），比如在第3页，但page值却为2，这时候音量下键下一页就会去到page + 1，也就是第3页所以不会往下

**Comment by XianYuDaXian** [comment]
> @XianYuDaXian 可以试下 [v0.5.4](https://github.com/youniaogu/MangaReader/releases/tag/v0.5.4)
> 
> 翻不动是因为翻页后有概率page不会更新（android下会有这个问题），比如当前在第3页，但page值却为2，这时候音量下键下一页就会去到page + 1，也就是第3页所以不会往下

好的谢谢更新，测试了下最新版没问题了，翻页可以正常翻。还有就是能不能在开始阅读一话的时候支持向上一话翻页？比如说我点击进去第2话，滑动或者音量＋到第1话的最后一页？现在的话如果是从第1话翻到第2话的话，因为已经缓存了所以可以向上翻页。如果可以在没有缓存的情况下也能向上一话翻页的话，阅读体验就更流畅了。

**Comment by youniaogu** [comment]
向上翻页之前试着做过，但太多bug就去掉了，暂时不考虑吧
