### ISSUE TITLE
希望添加“已观看”，“最新话”等记录观看进度的字段

### ISSUE THREAD

**Issue by hot36952** [youniaogu/MangaReader#42]
**现有功能改进还是新功能/插件提议？**
新功能提议
**请简单描述下你的需求**
有些漫画观看进度会失效，我猜测是因为翻译组重新上传了修正后的某一话导致的？
订阅漫画多了经常忘记看到哪一话，希望能增加记录2个字段（“已观看”，“最新话”），显示在漫画详情页甚至是首页。
![4430503060138888204](https://github.com/youniaogu/MangaReader/assets/21011227/b1730052-5175-4208-8472-0ccd4cc0bbf5)
比如上图，我看到108话，可能是翻译组后来修正了108话？或者更新了13卷番外？观看进度失效了，虽然此时还有个缓存标记让我能知道自己的进度，但是如果因某些原因清空了缓存，就不能直观看出观看进度了。

**Comment by youniaogu** [comment]
这样子吧
<img src="https://github.com/youniaogu/MangaReader/assets/13073995/3a0172ec-3174-4a25-81c4-bb76ab170f65" width="300" />
最新话更新后会出现在最前面，很容易看出来就不加了

**Comment by hot36952** [comment]
> 这样子吧 <img alt="" width="300" src="https://user-images.githubusercontent.com/13073995/244569582-3a0172ec-3174-4a25-81c4-bb76ab170f65.png"> 最新话更新后会出现在最前面，很容易看出来就不加了

不错，详情页面多个上次观看就够。
![15101161471519175094副本](https://github.com/youniaogu/MangaReader/assets/21011227/312dd53c-4be5-4445-af5e-2534ac245790)
添加最新话的作用主要在首页，更容易看出哪个是真更新，哪个是假更新。

**Comment by youniaogu** [comment]
首页不加了，1是排版不好看，2是这种情况很少见

**Comment by youniaogu** [comment]
[v0.5.4](https://github.com/youniaogu/MangaReader/releases/tag/v0.5.4) 加上了
