### ISSUE TITLE
JMC的条漫显示不全

### ISSUE THREAD

**Issue by TOMJacksom** [youniaogu/MangaReader#43]
谢谢大大开发的这个app，太喜欢了！最近发现，JMC的条漫显示有些问题，有的图片只显示了一部分，有的图片重叠在了一起，还有的蛮模糊的。

麻烦大大抽空看看，谢谢啦！

**Comment by youniaogu** [comment]
可以提供下复现步骤吗

**Comment by youniaogu** [comment]
已修复 [v0.6.0](https://github.com/youniaogu/MangaReader/releases/tag/v0.6.0)
