### ISSUE TITLE
下载路径不支持储存卡吗？

### ISSUE THREAD

**Issue by 110120911** [youniaogu/MangaReader#44]
大佬，能添加一键全下载吗？那些漫画多章节的，想全部下载得一个一个按单章节下载，实在有些麻烦。还是说能一键全下载但我没看到？
还有下载路径不支持储存卡吗？

**Comment by youniaogu** [comment]
储存卡你可以试下修改下载路径，在About页里

**Comment by 110120911** [comment]
试过了，下载不了。
![Screenshot_20230702_145956_com.mangareader.jpg](https://github.com/youniaogu/MangaReader/assets/66151534/6857f1b9-ebd6-4066-847d-18f7954eb908)

**Comment by youniaogu** [comment]
`/F71E-7CAB/漫画`这个文件夹目录是已经存在的吗？

然后可以截图下你目标文件夹的info吗，像这样：
<img src="https://github.com/youniaogu/MangaReader/assets/13073995/f9886ef1-a7b6-4fb2-ad1f-fb971ea5f9b6" width="300" />

**Comment by 110120911** [comment]
好的
![Screenshot_20230704_052928_bin.mt.plus.jpg](https://github.com/youniaogu/MangaReader/assets/66151534/49e63925-87b5-428f-8bbe-1b1ebff73a68)

![Screenshot_20230704_052851_com.huawei.filemanager.jpg](https://github.com/youniaogu/MangaReader/assets/66151534/13da6594-99bb-43e0-a8be-c02be2e01531)

**Comment by youniaogu** [comment]
默认的下载路径有用吗，可以发下你默认的下载路径吗

你可以把/F71E-7CAB去掉试下

**Comment by 110120911** [comment]
/sdcard/DCIM
默认的下载位置可以下载漫画，然后按你说的去掉/F71E-7CAB也还是下载不了。
![Screenshot_20230704_193213_com.mangareader.jpg](https://github.com/youniaogu/MangaReader/assets/66151534/08c201fe-cfa4-4fea-864b-3588bcbc3d05)

**Comment by youniaogu** [comment]
所以你这是额外插了一张sd卡吗？（我的安卓机不能插sd卡，还在想办法复现中）

然后创建目录只有在检测到没有该目录时才会执行，当你的目录已经时创建好了的，所以目前看下来比较有可能是下载目录不对

可以再试下这些目录`/sdcard/漫画`，`/sdcard0/漫画`，`/sdcard1/漫画`，`/storage/sdcard0/漫画`，`/storage/sdcard1/漫画`

**Comment by 110120911** [comment]
是的，我是额外插的是sd卡，sd卡路径下载不了漫画，手机的内部存储路径可以正常下载。

**Comment by youniaogu** [comment]
[v0.6.0](https://github.com/youniaogu/MangaReader/releases/tag/v0.6.0) 新增了批量下载

**Comment by youniaogu** [comment]
bug部分我另外开个[issues](https://github.com/youniaogu/MangaReader/issues/44)，这个先关闭了
