### ISSUE TITLE
二维码恢复数据能支持阅读进度吗

### ISSUE THREAD

**Issue by shibuyameltdown** [youniaogu/MangaReader#45]
*现有功能改进

rt，因为ios经常要自签，有时候手抖自签选错设备码，就需要恢复数据。
但是现在用二维码不能同步观看进度。
不知道能否实现

**Comment by youniaogu** [comment]
加在剪贴板备份那里吧，二维码新版本打算去掉了（相关依赖没更新，然后数据多的话会生成失败）

**Comment by shibuyameltdown** [comment]
好好好

**Comment by youniaogu** [comment]
[v0.6.0-rc.2](https://github.com/youniaogu/MangaReader/releases/tag/v0.6.0-rc.2)，备份和恢复增加了阅读进度
