### ISSUE TITLE
copymanga的条漫显示有问题

### ISSUE THREAD

**Issue by dfmjndm** [youniaogu/MangaReader#46]
以我独自升级为例，图片有接不上去的情况，就是上一张图片的下部和下一张图片的上部对不准，另外条漫的加载延迟有点高，滑下去图片都没加载好，可能要增加预加载量或者别的方式解决一下

**Comment by dfmjndm** [comment]
在官启上显示没有问题

**Comment by youniaogu** [comment]
copymanga没有条漫的吧，可以分享下具体是哪部漫画吗

**Comment by dfmjndm** [comment]
> copymanga没有条漫的吧，可以分享下具体是哪部漫画吗

我独自升级

**Comment by youniaogu** [comment]
你能按issues模版提供下相关信息吗，不然我很难复现和解决

**Comment by youniaogu** [comment]
无法复现
