### ISSUE TITLE
收藏按键一直是红的，导致没办法收藏漫画

### ISSUE THREAD

**Issue by bulilante** [youniaogu/MangaReader#47]
**非常感谢您填写错误报告！**

**以下是一些注意事项，请务必阅读**

- 提交报告前请检索相关 issues，避免重复提问
- 提交报告前请先尝试浏览器里访问原网站排除网络问题
- 请按下边 issues 模板要求提供相关信息，避免挤牙膏式提问

---

**问题描述**

**如何复现**

**错误信息**

**设备信息**

**Comment by youniaogu** [comment]
你用的是rc版本吗

**Comment by youniaogu** [comment]
这个bug已经修复了，可以等下v0.6.0正式版或者先退回v0.5.4

**Comment by youniaogu** [comment]
[v0.6.0](https://github.com/youniaogu/MangaReader/releases/tag/v0.6.0) 已更新
