### ISSUE TITLE
再推荐一个比较全的网站 务必添加 copy漫画能看的太少了

### ISSUE THREAD

**Issue by JONREAN2** [youniaogu/MangaReader#49]
https://www.comicabc.com/

需梯子

**Comment by disjoint0530** [comment]
👍👍

**Comment by youniaogu** [comment]
谢谢推荐，今天研究了下，我发现这个网站有不少问题

这个网站并不是纯漫画的，搜索出来会有动漫（搜咒术回战下会有个`咒術回戰Ⅱ`），漫画缺少单独类别和分类，并且最多只能翻10页，所以就不加到应用里了

作为替换我打算添加 [mangabz](https://mangabz.com/)（需要代理），访问速度和更新速度都挺不错的

**Comment by JONREAN2** [comment]
ok


JIGU ***@***.***> 于2023年8月7日周一 17:12写道：
