### ISSUE TITLE
爱了爱了💕加油！

### ISSUE THREAD

**Issue by disjoint0530** [youniaogu/MangaReader#50]
太强了，正愁没有这样的集成app，我也很爱看漫画，但是希望能把漫画图片扩大至全屏，感觉放大看有点麻烦。。。😍😍

**Comment by disjoint0530** [comment]
没事了，发现上下时是全屏

**Comment by disjoint0530** [comment]
为啥会出现cant read property

**Comment by disjoint0530** [comment]
今天凌晨还有问题，现在突然没了😓

**Comment by youniaogu** [comment]
那应该是网络问题，遇到时切换代理或者开关APP就好了

关于报错，现在这些报错文案都是直接抛出来的，比较有迷惑性，后面我会统一修改一下，变得更容易理解一些
