### ISSUE TITLE
增加下载漫画时显示百分比进度，增加下载失败时重下失败页功能

### ISSUE THREAD

**Issue by hot36952** [youniaogu/MangaReader#51]
v0.6.0的“下载”似乎相当于旧版本的“缓存”，现在下载时右划界面只显示下载中的“第11话（菊花）”和下载完成的“第22话（X）”，这个X是否代表下载失败的页数？
希望可以增加标题功能，下载中的“第11话（50%..菊花）”，下载完成的“第22话（X页失败..点击重试）”

**Comment by youniaogu** [comment]
重试命中缓存bug已修复，[v0.6.1](https://github.com/youniaogu/MangaReader/releases/tag/v0.6.1)
