### ISSUE TITLE
进入漫画章节后音量会固定在大概25%左右，调节不了音量

### ISSUE THREAD

**Issue by 410676306** [youniaogu/MangaReader#52]
进入漫画章节后音量会固定在大概25%左右，调节不了音量，退出漫画章节后会回到原来的音量。在漫画章节里调音量只能先切出软件再调，而且只要调音量就会让漫画翻页。软件版本是v0.6.0，手机ios。

**Comment by youniaogu** [comment]
是这么设计的，因为音量不变化不会触发事件（0时减音量，1时加音量）[#17](https://github.com/hirbod/react-native-volume-manager/issues/17)，所以只能锁死音量
