### ISSUE TITLE
下载后导出漫画报错创建文件夹失败

### ISSUE THREAD

**Issue by rusthx** [youniaogu/MangaReader#54]
**非常感谢您填写错误报告！**

**以下是一些注意事项，请务必阅读**

- 提交报告前请检索相关 issues，避免重复提问
- 提交报告前请先尝试浏览器里访问原网站排除网络问题
- 请按下边 issues 模板要求提供相关信息，避免挤牙膏式提问

---

**问题描述**
下载后导出漫画报错创建文件夹失败
**如何复现**
随便点击一本漫画，长按目录后下载，下载完成后（颜色变成最深的颜色）导出报错创建文件夹失败

**错
![Screenshot_20230812_213727](https://github.com/youniaogu/MangaReader/assets/125135983/b9ba121b-69b7-450d-9bbe-f29a8157d0a5)
误信息**

![Screenshot_20230812_191705](https://github.com/youniaogu/MangaReader/assets/125135983/0bfd0a8e-da9f-4246-84d2-8263a3a6238b)

**设备信息**
vivos6

v0.6.1

**Comment by youniaogu** [comment]
这种情应该是导出路径错了，试试像`/sdcard/Download/MangaReader下载漫画/漫画名`

或者依据你默认的路径去相对得修改
![屏幕截图 2023-08-13 113224](https://github.com/youniaogu/MangaReader/assets/13073995/edb18c96-c83a-4490-820a-e9bee09cfacc)

**Comment by rusthx** [comment]
谢谢解答。我将导出路径改成'/sdcard/下载/MangaReader下载漫画/与雪女向蟹北行'后，可以正常导出。
![Screenshot_20230815_085127](https://github.com/youniaogu/MangaReader/assets/125135983/c71ac5eb-2544-4bb6-9fa8-f702ae37ef1b)
