### ISSUE TITLE
有一个小提议

### ISSUE THREAD

**Issue by JYLpp** [youniaogu/MangaReader#55]
希望能增加一个新功能，让漫画右左翻页的顺序，因为日漫很多都是右左顺序，希望可以实现🥰

**Comment by youniaogu** [comment]
这个功能已经有了，最上面页码左边有个方向箭头

只不过刚才发现有bug，会使当前图片上下或左右颠倒[#860](https://github.com/Shopify/flash-list/issues/860)，切换后重新进出就可以了

**Comment by JYLpp** [comment]
> 这个功能已经有了，最上面页码左边有个方向箭头
> 
> 
> 
> 只不过刚才发现有bug，会使当前图片上下或左右颠倒[#860](https://github.com/Shopify/flash-list/issues/860)，切换后重新进出就可以了

**Comment by youniaogu** [comment]
我知道什么问题了，已经修复下个版本更新
