### ISSUE TITLE
禁漫的图片加载有彩色横条

### ISSUE THREAD

**Issue by zknbnbdnb** [youniaogu/MangaReader#56]
![6f450f78037ec6f51861104ee560658](https://github.com/youniaogu/MangaReader/assets/70320698/604bdc0b-207c-41c7-9f65-bce7ed289b8a)
这个软件非常棒就是禁漫有点小问题，nh加载有点慢就是了
作者做到了我大一统的梦想

**Comment by youniaogu** [comment]
横条的问题我昨天彻底弄懂，已经修复了  [06cf70c](https://github.com/youniaogu/MangaReader/commit/06cf70c7bf4a4c6a06a18e765d9d3195f2189eb7)，下个版本更新
