### ISSUE TITLE
关于平板页面布局

### ISSUE THREAD

**Issue by ryanwuson** [youniaogu/MangaReader#57]
您好，我是iPad Pro及M1 Macbook使用者，非谢谢您开发这么棒的软件！
不知您可否增加一个大屏幕可以同时显示左右双页的布局？
可提升在大屏幕上的阅读体验（更像在读纸本书）
再次谢谢您

**Comment by youniaogu** [comment]
[v0.6.4](https://github.com/youniaogu/MangaReader/releases/tag/v0.6.4) 已更新，使用过程中遇到问题欢迎issues和pr

**Comment by ryanwuson** [comment]
谢谢您
