### ISSUE TITLE
下载时的问题

### ISSUE THREAD

**Issue by wqc7741** [youniaogu/MangaReader#60]
手机为k60至尊，最新0.6.2版本
下载时出现问题，出现一行小字
手机256g，空间足足
![Screenshot_2023-08-28-18-59-28-603_com.youniaogu.mangareader.jpg](https://github.com/youniaogu/MangaReader/assets/143375767/4d03d29d-3575-4ba0-8c70-23bc0e89ce3c)

**Comment by wqc7741** [comment]
现在不断弹出这一行小字

**Comment by youniaogu** [comment]
安卓离线存储超大小限制了，单条读取限制2M，总体写入限制6M

**Comment by youniaogu** [comment]
已修复 [v0.6.3](https://github.com/youniaogu/MangaReader/releases/tag/v0.6.3)
