### ISSUE TITLE
恢复备份没有同步上次观看记录

### ISSUE THREAD

**Issue by shibuyameltdown** [youniaogu/MangaReader#62]
rt
设备ipad mini4，系统ios15.7,软件版本0.63

备份信息：N4IgxgTgpghgLlAKgSwLZRALgIwDYCcATIfgAyEDM+uppANCAGYwBuA9hMggM5YDaIAMIB5AAoBNAGQBPZNwAWyAFbIoAdxgA7FTGltNAcwAmUQyuwrNAD2SGAXgFdkAR2RaDj5AGsHMZCekQBhEJSTB5UwM1KC4YEwNfTQAbZDsIgCMYIKExKTgnGwckmDZUNg1DI30DBS07P1dskKlpGG4lTTA1aXa7ZybcyVRbAzg3Q0SPCJ02YuRMgdC0qGhNLyh0hwVkNX0tPQdFqQMoZaSWSxNNFgAHSIOjyXSY2WdEzM1PI2U3VD9vkomXbbFS1QwKBxpVJOR5lNQOdCGKAnGyaeS+ZAJWLIR5aGxaFL2dEBBw+PyE4zIZiGaQOWQKSLhdw2Mq8YKDWRpSbPVKKRxsGxePwJGCWSJ2ZAHeIONjotiPaRKKxJOw9NKMLpKIzSVDSOBGVBGeRGRh2NSodJm6SW6RGqz9dmhdKqNIwAxaXZteTuVb4tgqDCOqTcNRGJSoKx2IxqS1qeTpaRRtTOCDcOzpNSdNk5ULcCAGMDtdI3ZxJLzpJTObjcIyRrVGO3OdKPBmaYaVGCrd1sMAypKBnNSfE0kr1SVyRQBhKlLStgxyx4GarcZDyNgOHnbMrMbaPZzSDWq7iF+RwGvcAy2x4azTcHpKQtJa8bLUxuxgJKJ6OPdGuOCR6N+w7TRHmHCAMQiEw4XcIxO1MR4eT+AVxmWIVkHCBw10hGVomQFItEsCFtnCapUQdQcZAnH4oGGJd7CcVsMNw1ANzceUg0kOUTE2AwxUMTRkAcWDNCBNg0NcDRMV8VY50eXZhIMHk4D8a4DhUBxUQMftYVYkpwkiXDW22EwuTgddVjk0pTE2dFV18KwHCXBEtHRLIOOdQxcO+fF9MqKBGB6RR4UeTxwLYUS9EMDCtFcdweOdGLxgMELXNvCJDA+WlDGqAIqKnaokgcfy3IonQ0hyqAFHXFZrhuQ4OL6VB5CUT95Gaz57y8NRs2aIYXiKGB0Ds/wnBgV0dlMCB10XJRuvSOBbUTJtUDsbgSt6vwhtcOipnqiixi0MBNv0FghrKbSONgtg7BiHRDEeANmEe9bBnbSl+JYB4OMsLSRhXAMhukKAgdgidIhOSzUXKvygaqvbeqhdEUlg5xjEyYYFUSKdZ3SnRHl8qIYjGKA7o8Px6UnVQjEcmUDjA0xZI4+RXEMIauT+OwlHSeRpHwzQ/CsJQHvGLRYNWbjhRibYaP9HEOJZgwBNst5MlFQTLDMwwHIHXq/ThqElAcTRnSgBBPPYiiEzsOAwGjaM0lPQ1UBWown2+orNPw2Y1b4iUqjMWxTFkHbbI0GYTGgWE2M2dZWhAjjWjYE40vXAT3ERTWPCcP5HmprQzIcZT/CgVE061tjrglTYjqo2zhkqymoBMSz0s+9coJiIaA2iZIdcGMACocVY0OM03Z1pkYbGqZTUBC3RIXn+paWKNhdwapQlAgIx0kNatoxueQ7CibV2gjBRXaSbm1CFji+c2KFUT0NhpGcMAo2cFbZ44o7NDL653WNhuAa3gSaqHAnhGAfoAwhVNuMLw64V7bH5uFHKiQbjjBUD+WBJQSxRk4EyQwbw14UVkAHQwmdtbDkUjELksgrqYwiLsZYcdjD+RiKsGYFRWGqWmgnaoyx4TMGUmtQw5x8hyTpDsUkgJTAsG9HLS2Vh0gBWcM4RgoZD5qE/G/IwzgvDcDdhReSwM8pUy9ARBRvUFYYU0K4KBVNgaHXSgYakLiXqhHxENUGiDFDgW2BCC2vVh5N1OBscYSFhyYIak4H6QlZF1SlElDEoFxi2QOHY1JGk2LQI4v4yI9ioDenKA4VxPIFTzBUuMEw+RLGDEKhhK6cdHgCVbAlESJc2KtnhCkVYrkUmpQjqYLhKhQZxxan3UImd+QmE0jKChRUilUJsKlXYudkA+WccjKACs2bohzhxXCEBRwRDhHEhyKctiKDnAuBOkCkoFMEboO5WgYCMFMI/WpoRSG4R0JuIp/YVhV1HC4YuuxIq8VsHOEwsUQr3iSJebglVwxyXcE5PiBhxLjhBKoIa2woTnAhBOJwJhYJfwotDRW4x+btIptRLhTlrkyhSpEIuw5ljbCBlhBU/D0qixKPI0OMRqR+ixPsiiDI7pglYd5NwBNuVEibnBT4tMG7EqgOsIp8qs6qHRWheEEIYImOxYU9cO0RT+BgDcOAzS24OAJtTT5UhQQaQ9mxEySNJQTKHKoVs8yOnuETqQn+yVb7oSKVBco7g5XuRiPIq6MzxiyBSCsayMRvhCRKLSnJFE3h1H8NUUhv0iT8sSLiPCkJFCpT5n4TIYbJQlJiEyLg4xiG9U2InPma5RHIkSCxP1KLDBosDoYTFWacVSz5Ioc4A7tjwnGmbYwmbTFeskFQo5I7YDFylYi3CuwfCaCOYEwYEQUJFNSni/46y3DVt5NUZpeI3XA0uSy0iRV8apQiIwOJ27eSmHWH4fGV6ShYjzpodBFjsgABEACyAAtAAUpIEg+AADsFA54/AJMuZxSsSgyWcYuZEhSx4mBEZkNgRczqd3ggAXQYMUbgcAADq8BwhYFAL1ROyc4ZlwMBnfh2csiYFAEyK1KwsAkOAwzLCvH+P0TQDASQAAWGAFB0i4CMEdAAtIwXAuAACsWnsDYCblp6ghAoBafIEpig+nCBKbs2AKApBshjDgNpTAIBAA03tgFDgBd6OyDcN0GAcAAF8OLDBKDHRxIFhPgG9GJiAEneqRbYNFuOkhaC4AABzqcYNlrTJBsCGeM1ASz6QUMqa00YCgRhiDZZgChjTUBcCua4B57zKHSB+cAKvRgBod0C8FrA2BwulVdaItixQVC+3zWQoOmJqihzVjIyOcXRMICS553qhsOkTZKFNn4mhTB+2qHxYOi2nBh0fdASQuBnhgHwLBQgWmm76cs6VowWn0iEBQ2AKz9nbP2cc85tr7mQveYMwFhgQWIZhfcomG2ds1AOzgE7F2T41sJY28lwYVtEehmR21VHBp0eSEe/gfAFByB/ewIQZRRmTOWZgGAMAuBqu1fq415rrWGBuY6153AAA6fTgBHKMG7DkbHE9ZYQNkbE2C7VmY8tdjrbgxpfrll8bVQCu2CSCgPppTd3CAwFIEZigFAUMM7K1p5nLX2d1cIA1prJgecgD5+Drz+nRfi5C5LnNIwlZOBVjANWDgNavpCyJrH4nVehAVoHlwG4Q/qXD1rIqkgUMbH0/gdIqGXuaYKx9szdPLfWcBw5wgTmXO8/ax77ASnus++G6N7bIsRJKolpiCdOLZbsfi8rmPpU29i1MJ3k4VEZYqAz05pu2AqdGY1CVkzn3VP6fSP9mzdmK9V9B/z7ApAxfQ6G3DiizMRi7OcpzbmvMRbrKFkrxLOPQhn9ZjQvZY0uY8xvYLSQ+nsDpCU2y2yzsxt3wCU2wCtz+xgCAMYA33L2B2rzd1rwky81IGwChxABhxCwoBb37mcVwmJlJjHDHSbhpmfnXHpjSkiD73W0H16gJgIJ1SSmIOXWpmnDpnGHw0iEkAbFwEIFIBQ0rys1gGe1KyZ3SH00txqwdyd2513zr3wEF0IAwKwObwTixlUAAVbDxgfxVxIQ0ORBxlMB0CeBQxQ2y3APUys30zQKtyZ2y2wHwHt052dxa3kJQPwH0xUOPz9wRkrSKAtVRm3kGhxF0LoMGERgCJRjRhCN/zXyMCUzAAoCUx0wazZyL1UyU3XzLy3wQPcM8y80IC8KbxP16l2Chi7VYVhi5TCM2yMWQk+EqICAbnXFuwq1IBgCgCEOywe3XyLwaygAKxyKB0rxBxrzBxQOM3QJKN8MGB+gpH+nHU9RBj8DnFhyjwHzqNbwm3BGokBmBkVTBkHSgDCGc3AI6JgAZxQ0+1KygNIF0yszQNwAoGcyOniPyO8zQO8Il1wNCDem+A+geFqKfykH+ID1tTCASIN2UTZ3sySLsK+302yycOkJcLkPGL32KKPx+O+lUCejxKEw2Mf1jydQJOegzze1IFszeUKyKPe0Zy+yU3wFgNRMdy5xdw+J80b2xN91+KkCuhukw3umBJJJ4NHFuiSiQwoCAOoH3yMzK1gLEK+0IG3mcLZNcNd3d0mIoG+N5I4gOk6GOmuDOlmEj372JP2nGBrjKGNM7lNMkEYB+woGwBgAsyM1wEYEVIZM6P8jVNkI5IxI90d0P0wJ8L5MkE2hiG2h5UOBFIokjJBR2i5EkBeJa0YCMFIELxsJp29Ngks1ZP9LcMDJQNIG9x5LUIol4jmgWm1D6B3lWkJPNL0N6irO4HmkWjrJWjWkkAcPwGc2oFNygGZMLxMygKMGy1LwB1yNGMQK1IKOK0F2mPLNKNen6mKCGlsgdTGnkR7imljKJObNXPrXXNjWJVGnGl3NaIp0YFoFglgKgHNyX1MwAJVLgOnJ32LPnLLNDJxPJQ/malanaiPCUC6l4DjIRn/JamkDag6GAtAtOOy0YHNxdK0yU31xSNuJt1ICsOGO3zGKQImPnN1IrNb23IqjhhqluH3KbPCNCDKiaJaKKggFqgcDCBZwoEYCROe3NxgAgKVPSHSDUz9PZKLIIv534JDNUJXKWHPWcUyiNh2lymNR2kKmKhoOjy2IiNksiHkuyhhmXRUqKmYCeAcItxePSKMGZIRO+1wAgILJEs1OQIKK+JmPDNChlAimqGilsSSninGFimFIPNoqkHcvCnUHIKilSgCsUkcjaWip4KMFwBgBy3y0KyRJzOtwkMdOEo1M5OK0krDPchGC8iA3tX8kCikXUs2JBKeGKrTVKucRMAClnVYtgEcPSBNDZ1ICMDnwRJDwfJyvRLErryxJ/L1PqMRBsicFcgcicj+DRF8CqotLKKskAVshmscnXHmtcjCH0xq0YEq1NxvMsqt0+08OZzfJGI/OGpLIoAKp+NC1CyAA

**Comment by youniaogu** [comment]
没问题呀，我用你的备份信息恢复有同步观看记录

但是只有26个漫画有观看记录
![image](https://github.com/youniaogu/MangaReader/assets/13073995/86721e63-fab9-41dc-bd11-71db45196a66)

**Comment by shibuyameltdown** [comment]
> 没问题呀，我用你的备份信息恢复有同步观看记录
> 
> 但是只有26个漫画有观看记录 ![image](https://user-images.githubusercontent.com/13073995/266812113-86721e63-fab9-41dc-bd11-71db45196a66.png)

那感觉可能是备份的时候缺失了？因为我记得挺清楚上次有一部看过的这次也没记录

**Comment by youniaogu** [comment]
@shibuyameltdown 备份后面我想改成文件备份，这样就不存在大小限制，类似的丢数据问题应该也会少很多

**Comment by shibuyameltdown** [comment]
> @shibuyameltdown 备份后面我想改成文件备份，这样就不存在大小限制，类似的丢数据问题应该也会少很多

字词
