### ISSUE TITLE
漫画柜的搜索和首页都无法显示

### ISSUE THREAD

**Issue by XianYuDaXian** [youniaogu/MangaReader#64]
**非常感谢您填写错误报告！**

**以下是一些注意事项，请务必阅读**

- 提交报告前请检索相关 issues，避免重复提问
- 提交报告前请先尝试浏览器里访问原网站排除网络问题
- 请按下边 issues 模板要求提供相关信息，避免挤牙膏式提问

---

**问题描述**
安卓版漫画柜的搜索和首页都无法显示，本地网络确定可以上漫画柜网页，已收藏的漫画也可以正常观看，但是搜索和首页报网络错误。IOS正常。还有安卓貌似使用了不同的包名？0.6.3安装不是覆盖安装
**如何复现**

**错误信息**

**设备信息**

**Comment by XianYuDaXian** [comment]
哦，原来是缓存，安卓的无论是搜索还是阅读都不行了，又是header出问题了吗

**Comment by youniaogu** [comment]
很奇怪我安卓没能复现，是MHGM那个插件吗

安卓在0.6.1时修改了应用id，所以前后版本没法覆盖

**Comment by youniaogu** [comment]
> 哦，原来是缓存，安卓的无论是搜索还是阅读都不行了，又是header出问题了吗

我在安卓手机（v2rayNG分应用代理和全局代理）和postman上试了下，还是没能复现，非常抱歉

<img src="https://github.com/youniaogu/MangaReader/assets/13073995/8880802f-4eac-448e-9b16-e2b8615f0b64" width="720" />

你可以尝试下切换代理的ip，本地网络确认时记得用无痕模式
