### ISSUE TITLE
大佬可以添加韩漫网址吗吗

### ISSUE THREAD

**Issue by sakurrasama** [youniaogu/MangaReader#67]
**现有功能改进还是新功能/插件提议？**

**请简单描述下你的需求**

https://hanman18.com/ 这个网站不错

**解决方案**

**Comment by youniaogu** [comment]
漫画源有点少，而且有些漫画缺少章节

![image](https://github.com/youniaogu/MangaReader/assets/13073995/7fd41093-38e4-47d8-b352-a99ea21c97d2)
<img src="https://github.com/youniaogu/MangaReader/assets/13073995/ec80a83f-b794-4886-858c-ee14cc43693a" width="480" />

有其他网站推荐吗

**Comment by sakurrasama** [comment]
> 漫画源有点少，而且有些漫画缺少章节
> 
> ![image](https://user-images.githubusercontent.com/13073995/275372689-7fd41093-38e4-47d8-b352-a99ea21c97d2.png) <img alt="" width="480" src="https://user-images.githubusercontent.com/13073995/275372627-ec80a83f-b794-4886-858c-ee14cc43693a.png">
> 
> 有其他网站推荐吗

https://www.ikanmh.xyz/ 还有这个

**Comment by youniaogu** [comment]
[肉漫屋](https://rouman5.com) 打算加这个，应该不会太快倒闭

**Comment by youniaogu** [comment]
[v0.6.6](https://github.com/youniaogu/MangaReader/releases/tag/v0.6.6) 已更新
