### ISSUE TITLE
最新版本JMC无法访问

### ISSUE THREAD

**Issue by JYLpp** [youniaogu/MangaReader#68]
![IMG_8099](https://github.com/youniaogu/MangaReader/assets/130224929/8b000bce-b713-4b98-a6f0-5ebbb2ca5340)
从插件页面直接进入网站也无法加载，已开启代理的

**Comment by JYLpp** [comment]
![Uploading IMG_8100.png…]()

**Comment by JYLpp** [comment]
![image](https://github.com/youniaogu/MangaReader/assets/130224929/d8dc542f-fa45-4991-82d0-2c083800d924)

**Comment by youniaogu** [comment]
禁漫天堂那边挂了

**Comment by JYLpp** [comment]
> 禁漫天堂那边挂了

好
