### ISSUE TITLE
收藏被清空，提示xx同步失败

### ISSUE THREAD

**Issue by hot36952** [youniaogu/MangaReader#69]
**问题描述**
前几天从v0.6.3升级到v0.6.4，升级完我马上备份了，一直整成使用，今天早上打开app提示xx同步失败（没看清），收藏被清空了，重启后再无提示，还好我前几天备份了，只好恢复。
iphone 13 ios 15
![F8Z68$5YCQ` K7Y4P~E~{T3](https://github.com/youniaogu/MangaReader/assets/21011227/0f815ceb-9cd9-4d37-b812-552f52da7acf)

**Comment by hot36952** [comment]
今天早上还正常使用着，就在刚刚，打开app再一次提示xx同步失败（我直接呆住又没截到图），这次又要恢复到一周前的备份了。。

**Comment by youniaogu** [comment]
[v0.6.5](https://github.com/youniaogu/MangaReader/releases/tag/v0.6.5) 已修复
