### ISSUE TITLE
v0.6.5版闪退

### ISSUE THREAD

**Issue by ljy5201314** [youniaogu/MangaReader#71]
v0.6.5版选择章节后打开漫画就闪退，安卓版本为12,系统是realme ui 3.0

**Comment by ljy5201314** [comment]
写错了，是v0.6.5

**Comment by youniaogu** [comment]
是哪个插件闪退

**Comment by ljy5201314** [comment]
> 是哪个插件闪退

我打开的是kl的漫画

**Comment by youniaogu** [comment]
重新发版了

**Comment by ljy5201314** [comment]
> 重新发版了

还是出现闪退，而且其他的插件都会出现

**Comment by youniaogu** [comment]
![image](https://github.com/youniaogu/MangaReader/assets/13073995/df11e2cf-3549-4421-931e-51e90e95c266)
有刷新release页面吗，注意右边的更新时间
