### ISSUE TITLE
批量更新js vm memory问题闪退

### ISSUE THREAD

**Issue by rowenahxt** [youniaogu/MangaReader#72]
ios端0.6.3最近几周开始出现的问题，同版本之前也没遇到过，更新到0.6.6问题还在（大概是因为最近又添加了几部
```
MangaReader[34387:6766278] [javascript] ┘
W1105 14:09:47.729962 1810935808 JSIExecutor.cpp:378] Memory warning (pressure level: 1) received by JS VM, unrecognized pressure level
```

收藏有200+，批量更新剩余大约130～140出现这个报错闪退

可以麻烦查一查吗谢谢

**Comment by youniaogu** [comment]
谢谢反馈，可能是有内存泄漏，我要去测试一下

**Comment by youniaogu** [comment]
方便提供下备份数据吗，目前测试批量更新420本copy漫画没出来闪退

**Comment by rowenahxt** [comment]
[MangaReader备份数据2023-11-06.txt](https://github.com/youniaogu/MangaReader/files/13264175/MangaReader.2023-11-06.txt)

现在剩199本，导出前测试在113崩溃

**Comment by youniaogu** [comment]
![image](https://github.com/youniaogu/MangaReader/assets/13073995/d72ca0da-8fdf-4a38-89db-447225dee571)
 
模拟器里内存很稳定（450～550左右），没有内存泄露

![截屏2023-11-06 17 05 13](https://github.com/youniaogu/MangaReader/assets/13073995/4bf703a5-6b9c-4cc5-8362-a30d7709bcd5)
![image](https://github.com/youniaogu/MangaReader/assets/13073995/7fc54550-2061-44b7-8a9f-3cb44680c9d7)

然后似乎有29本漫画不存在，这个正常吗

有其他能复现出来的线索吗，比如报错或者网络相关？

**Comment by rowenahxt** [comment]
这边使用的是ipados 16.3.1，从真机数据上看确实存在memory leak的情况（附录屏视频），我也不知道模拟器和真机的处理差异😂我试试更新系统吧

（这个漫画不存在是正常的，copy下架了，但不是他们造成内存问题，更新到它们前就已经崩溃了

https://github.com/youniaogu/MangaReader/assets/26662830/48e9d42b-6b80-474e-9d87-2628072304e4

**Comment by youniaogu** [comment]
@rowenahxt 可能跟OS有关，但我目前mac还在monterey 12，导致xcode最高只能下载到ios 15

我要去搜一下关于ipados或者ios 16内存泄露的相关问题，如果没有我再去升级macos去测试ios 16

**Comment by rowenahxt** [comment]
麻烦你了，我这边更新到16.7.2还是存在同样问题，但是这之前同样os16.3.1我记得在收藏170+的时候都没遇到过，但按照目前的大约更新80本就会崩溃，好奇怪😂

**Comment by youniaogu** [comment]
![截屏2023-11-10 10 38 49](https://github.com/youniaogu/MangaReader/assets/13073995/cdfadef7-e25e-4048-99fc-f64f45dec67d)

@rowenahxt 你有二次开发吗，备份数据里有些多余的字段（项目里不存在的）

**Comment by rowenahxt** [comment]
没有修改过诶，只是为了安装加了我的developer签名😂，附git status
<img width="519" alt="image" src="https://github.com/youniaogu/MangaReader/assets/26662830/46ffdff3-b89d-4d18-8e0e-b127b7ef88b9">

**Comment by youniaogu** [comment]
@rowenahxt 你可以帮我导出一份内存溢出报告吗，导入后我这边就可以分析哪里有内存溢出，很简单的，按下面步骤来就可以了

1. 打开Instruments工具
![截屏2023-11-10 16 35 58](https://github.com/youniaogu/MangaReader/assets/13073995/ffad77fb-053d-4c6c-bf77-64fcb0b3547c)

2. 选择Leaks水龙头
![截屏2023-11-10 16 36 59](https://github.com/youniaogu/MangaReader/assets/13073995/462f0deb-90ff-4f65-9d39-7bdd0ed1de89)

3. 选中你的设备和app，再点击录制，开始录制后就可以去复现操作
![截屏2023-11-10 16 38 15](https://github.com/youniaogu/MangaReader/assets/13073995/72bbe703-9301-49f3-bbcd-1637cc50fb10)

4. 保存前要先停止录制
![截屏2023-11-10 16 41 35](https://github.com/youniaogu/MangaReader/assets/13073995/4da53ec5-a59c-4b1b-8f28-d3b30d320d80)

5. 最后是导出报告
![截屏2023-11-10 16 41 55](https://github.com/youniaogu/MangaReader/assets/13073995/ffc10ccf-20c9-46af-bfad-6801f8424980)

**Comment by rowenahxt** [comment]
虽然allocation一直在～500m，但录制是因为崩溃自己结束的😂，文件太大，放在google drive了
https://drive.google.com/drive/folders/1Y-4_dxqhXOPggn8Rr2jOu-Hnnx6kpF0T?usp=drive_link

**Comment by youniaogu** [comment]
已修复，在整理代码下个版本发布，测试结果在下边

<img width="1440" alt="截屏2023-11-14 21 57 40" src="https://github.com/youniaogu/MangaReader/assets/13073995/5d6ecd60-6017-411e-9a63-0e3fdd0fec5d">

**Comment by rowenahxt** [comment]
感谢！辛苦了

**Comment by youniaogu** [comment]
已更新 [v0.6.7](https://github.com/youniaogu/MangaReader/releases/tag/v0.6.7)
