### ISSUE TITLE
平板双页模式从右往左翻页的时候页码是从左往右的，读起来很难受，能否将页码对调一下，如1,2变成2,1

### ISSUE THREAD

**Issue by ztszts777** [youniaogu/MangaReader#74]
**非常感谢您填写错误报告！**

**以下是一些注意事项，请务必阅读**

- 提交报告前请检索相关 issues，避免重复提问
- 提交报告前请先尝试浏览器里访问原网站排除网络问题
- 请按下边 issues 模板要求提供相关信息，避免挤牙膏式提问

---

**问题描述**

**如何复现**

**错误信息**

**设备信息**

**Comment by ztszts777** [comment]
另外，能否在非阅读界面也能横屏呢，这样可以增强平板使用体验
阅读界面的横屏只能向一个方向，能否跟随设备重力方向呢
横屏问题是copymanga原版客户端硬伤，非常感谢作者的软件

**Comment by ztszts777** [comment]
设备是matepadpro13.2
另外横屏模式下图片显示偏下，顶部空出一部分，图片底部一小部分不能显示![Screenshot_20231106_130640_com.youniaogu.mangareader.jpg](https://github.com/youniaogu/MangaReader/assets/147629842/b20f8444-b18c-4364-bb96-e0af0db910f4)

如图

**Comment by youniaogu** [comment]
1. 新增一个配置用来调换双页模式下的图片顺序吧（最开始固定为1、2是因为有些长图会切成两份，换成2、1顺序的话图片会连接不上）
2. 横竖屏方向这块我可以放开竖屏锁定（但频繁切换横竖屏可能会导致布局错误，重进页面就好，所以这方面如果不是太严重的问题我可能不会特意去处理）
3. 图片偏下这个应该是bug，要看一下

以上的内容下个版本更新

**Comment by youniaogu** [comment]
已更新 [v0.6.7](https://github.com/youniaogu/MangaReader/releases/tag/v0.6.7)
