### ISSUE TITLE
通过漫画信息页点击关键词搜索出来的漫画加载不出来

### ISSUE THREAD

**Issue by shibuyameltdown** [youniaogu/MangaReader#77]
rt，描述有点绕，附视频↓
https://streamja.com/MJaz3
应该不是网络问题，直接搜索出来点进去是可以打开的
设备ipad mini4，系统ios15.7，软件版本0.6.6

**Comment by youniaogu** [comment]
视频提示不存在，可以再发下吗

**Comment by shibuyameltdown** [comment]
> 视频提示不存在，可以再发下吗

https://streamja.com/jp6Z4
我重新上传了

**Comment by youniaogu** [comment]
收到，下个版本更新

**Comment by shibuyameltdown** [comment]
🫡

**Comment by youniaogu** [comment]
已更新 [v0.6.7](https://github.com/youniaogu/MangaReader/releases/tag/v0.6.7)
