### ISSUE TITLE
 突然不能用音量键减翻到下一页

### ISSUE THREAD

**Issue by XianYuDaXian** [youniaogu/MangaReader#78]
**非常感谢您填写错误报告！**

**以下是一些注意事项，请务必阅读**

- 提交报告前请检索相关 issues，避免重复提问
- 提交报告前请先尝试浏览器里访问原网站排除网络问题
- 请按下边 issues 模板要求提供相关信息，避免挤牙膏式提问

---

**问题描述**
 突然不能用音量键减翻到下一页，有什么日志我可以提供的吗，现在只能音量键加来上一页，下一页不行，我保留的0.5.6倒是正常。已经尝试过清除缓存和卸载重装，都不行。
**如何复现**

**错误信息**

**设备信息**
matepad paper
0.6.6

**Comment by youniaogu** [comment]
你把音量调到50%左右再进阅读页面试试

下个版本有修改音量翻页的bug，也可以等过几天发新版本再试下

**Comment by youniaogu** [comment]
已更新 [v0.6.7](https://github.com/youniaogu/MangaReader/releases/tag/v0.6.7)

**Comment by XianYuDaXian** [comment]
好的 我试了一下 已经正常了 谢谢 另外以后能不能增加定时翻页的功能 间隔最好也是可以调整  还有一个就是类似B漫的选页拼图 因为即使是双页阅读 有的时候他漫画的跨页一张是在第二页 一张是在下一次翻页的第一页 如果是B站那样可以选择前一页或者后一页进行拼图就好了

**Comment by youniaogu** [comment]
1、定时翻页很简单，就是页面控制器里东西太多了，要重新布局一下
2、没用过选页拼图功能，有动图或视频解释下吗

**Comment by XianYuDaXian** [comment]
就是视频这样的，因为现在的双页显示只能给12 34显示完整的跨页，有的时候会出现23才是跨页 现在应用的双页逻辑不能显示。

https://github.com/youniaogu/MangaReader/assets/20138259/cbab058b-b0c6-4a41-a960-7f59d433fb17

**Comment by youniaogu** [comment]
感觉像是一个弹窗，专门用来拼图片看的，现在的组件没办法直接实现，优先级不高暂时不考虑吧

然后暂时没有新版本的打算，定时翻页可能也没那么快
