### ISSUE TITLE
横屏顶边黑条

### ISSUE THREAD

**Issue by ztszts777** [youniaogu/MangaReader#79]
**非常感谢您填写错误报告！**

**以下是一些注意事项，请务必阅读**

- 提交报告前请检索相关 issues，避免重复提问
- 提交报告前请先尝试浏览器里访问原网站排除网络问题
- 请按下边 issues 模板要求提供相关信息，避免挤牙膏式提问

---

**问题描述**

**如何复现**

**错误信息**

**设备信息**

**Comment by ztszts777** [comment]
![Screenshot_20231117_113207_com.youniaogu.mangareader.jpg](https://github.com/youniaogu/MangaReader/assets/147629842/848af193-6958-4bcc-a243-ec2d082b789f)

**Comment by ztszts777** [comment]
如图，手机平板皆有，横屏图片不全屏

**Comment by youniaogu** [comment]
切换好后，试试退出重进吧

**Comment by ztszts777** [comment]
试过了，没变呢

**Comment by ztszts777** [comment]
都是p60和 matepadpro13.2

**Comment by ztszts777** [comment]
测试了一下黑条刚好是状态栏的高度，应该是没有全屏到状态栏的位置

**Comment by youniaogu** [comment]
1、截图里左边的白边是什么？
2、点控制器上面按钮切换的横屏，还是横置自动切换的横屏？
3、可以点开控制器然后截图一张吗，这样我好看布局

**Comment by ztszts777** [comment]
左边的白边可能是竖屏下的状态栏到横屏模式的提现（我猜的）
不管是点按钮横屏还是自动感应横屏都是一样的

**Comment by ztszts777** [comment]
![Screenshot_20231117_122940_com.youniaogu.mangareader.jpg](https://github.com/youniaogu/MangaReader/assets/147629842/003b134a-971f-44b1-9117-b5b04bb6efa7)

**Comment by ztszts777** [comment]
![Screenshot_20231117_123126_com.youniaogu.mangareader.jpg](https://github.com/youniaogu/MangaReader/assets/147629842/ddd8ccbd-48ea-4278-8505-77f1ad436cc9)

![Screenshot_20231117_123305_com.youniaogu.mangareader.jpg](https://github.com/youniaogu/MangaReader/assets/147629842/327a1ce9-73c5-4f12-a822-d9b99ace6072)

根据不同方向横屏测试，我猜测侧边白边可能是前置摄像头留的边导致的，上边的黑边应该是状态栏导致的

**Comment by ztszts777** [comment]
平板是没有侧边的白边的，只有状态栏黑边

**Comment by youniaogu** [comment]
感觉像是safearea有问题，要看下

**Comment by youniaogu** [comment]
![截屏2023-11-23 15 57 31](https://github.com/youniaogu/MangaReader/assets/13073995/9a9b7f05-41ac-4098-baa3-98c628f3e175)

![截屏2023-11-23 15 54 25](https://github.com/youniaogu/MangaReader/assets/13073995/631dd6a4-2f7e-473c-bee4-a7ea8d527083)

可能是因为之前我按官方建议修改了`react-native-safe-area-context`版本导致的，下次更新我会改到最新版本，到时候记得反馈下问题是否还存在，因为我没有设备复现

**Comment by youniaogu** [comment]
[v0.6.8](https://github.com/youniaogu/MangaReader/releases/tag/v0.6.8) 已更新，有空的话麻烦反馈下结果

**Comment by ztszts777** [comment]
黑条没有解决，![Screenshot_20231216_124749_com.youniaogu.mangareader.jpg](https://github.com/youniaogu/MangaReader/assets/147629842/97e030b5-9965-4143-875d-b3256021d45c)

![Screenshot_20231216_124809_com.youniaogu.mangareader.jpg](https://github.com/youniaogu/MangaReader/assets/147629842/346ac041-1d6f-4d76-a0df-d013b44db2ae)

如图
音量键翻页已解决

**Comment by ztszts777** [comment]
https://github.com/fumiama/copymanga
可以参考一下这个的代码，它是全屏没有问题，但是没双页

**Comment by ztszts777** [comment]
https://github.com/youniaogu/MangaReader/assets/147629842/5379f4f2-6a3e-474a-b6ee-c989aa14f196

**Comment by youniaogu** [comment]
已修复 [v0.6.9](https://github.com/youniaogu/MangaReader/releases/tag/v0.6.9)
