### ISSUE TITLE
作者你好请问能构建一个未签名的ipa吗

### ISSUE THREAD

**Issue by XianYuDaXian** [youniaogu/MangaReader#8]
我试了一下自己构建 但是去到pod install的时候出来一堆错误 看了下 估计是我xcode版本不对 但是也搞不懂了 能不能构建一个未签名的ipa呢 我可以装到自己手机上用

**Comment by youniaogu** [comment]
@XianYuDaXian 抱歉，我没有开发者账号，没法打包ipa给你

然后是pod install报错，可能是ruby版本的问题，可以看下你的报错信息吗？

**Comment by XianYuDaXian** [comment]
> 

Xcode打包未签名ipa的话 不需要开发者账号的吧 我之前也试过打包 现在没带电脑 得稍后才能给你报错信息

**Comment by youniaogu** [comment]
@XianYuDaXian 谷歌到了，我等会尝试上传一个

**Comment by youniaogu** [comment]
@XianYuDaXian 最新的[realeases](https://github.com/youniaogu/MangaReader/releases/tag/v0.2.7)里上传了ipa，你看下是不是这个

**Comment by XianYuDaXian** [comment]
安装好了，但是打开能看到 Logo 然后就闪退 

https://user-images.githubusercontent.com/20138259/199726088-6586cefb-c983-49a0-b525-17922b15075c.MOV

**Comment by youniaogu** [comment]
@XianYuDaXian 可能我打空包了，我不清楚哪些要一起压进去，能说下你之前打包RN项目的步骤吗

**Comment by XianYuDaXian** [comment]
> 
[就是打包成.app然后新建Payload文件夹再压缩成ipa，](https://iplus-studio.top/2021/01/10/iOS%E4%BC%81%E4%B8%9A%E7%AD%BE%E5%90%8D%E6%97%A0%E5%BC%80%E5%8F%91%E8%80%85%E8%B4%A6%E5%8F%B7%E4%BD%BF%E7%94%A8XCode%E6%89%93%E5%8C%85ipa/#%E9%80%9A%E8%BF%87payload%E6%96%B9%E5%BC%8F) 我就是照着这个做得

**Comment by youniaogu** [comment]
> > 
> 
> [就是打包成.app然后新建Payload文件夹再压缩成ipa，](https://iplus-studio.top/2021/01/10/iOS%E4%BC%81%E4%B8%9A%E7%AD%BE%E5%90%8D%E6%97%A0%E5%BC%80%E5%8F%91%E8%80%85%E8%B4%A6%E5%8F%B7%E4%BD%BF%E7%94%A8XCode%E6%89%93%E5%8C%85ipa/#%E9%80%9A%E8%BF%87payload%E6%96%B9%E5%BC%8F) 我就是照着这个做得

他们貌似都没处理RN打包出来的main.jsbundle，我把资源放进去重新打包了一个，你再试一下

如果还不行的话，我只能帮你看下pod install报错的问题，这样你能自己build到手机里

**Comment by VCE1** [comment]
我使用Trollstore安装了realeases里ipa，测试了没问题。

**Comment by youniaogu** [comment]
@VCE1 谢谢反馈

我准备重新研究下打包这块，后续有进展的话我会更新在这里

**Comment by youniaogu** [comment]
@XianYuDaXian @VCE1  重新打包了一份[ipa](https://github.com/youniaogu/MangaReader/releases/tag/v0.2.7)，这份我自己测试了下没问题（爱思助手自签安装，手机未越狱）

**Comment by XianYuDaXian** [comment]
作者你好，这版能用，就是首页404，感谢。这几天换了电脑也就没了黑苹果了，你之前那版我不能用 我看搜了下有可能是构建的时候打包的架构只选择了你正在用的手机，所以有的人能用而我不能用。不管如何多谢。
![DA478A77-1FB0-493B-9582-4A2AB07E6772](https://user-images.githubusercontent.com/20138259/201521412-023097f3-c6fb-4da2-8af3-124568e10944.png)

**Comment by youniaogu** [comment]
@XianYuDaXian 能用就行，这里表达不太好，404只是指你还没收藏漫画，点上面搜索icon可以去添加，后面更新我会换个文案

**Comment by VCE1** [comment]
OK!我的ipad用trollstore安装也成功运行了
