### ISSUE TITLE
连续长按上一话/下一话报错

### ISSUE THREAD

**Issue by rowenahxt** [youniaogu/MangaReader#80]
**问题描述**

打开章节，长按上一话/下一话，在新章节再一次长按上一话/下一话会报错

**如何复现**

如上

**错误信息**

![IMG_4244](https://github.com/youniaogu/MangaReader/assets/26662830/7fc858a1-cc75-467b-b09d-ee05403fad17)

**设备信息**

ipad pados 16.7.2
app 版本0.6.7（这个bug我记得应该存在很久了

**Comment by youniaogu** [comment]
已修复，下个版本更新

**Comment by youniaogu** [comment]
[v0.6.8](https://github.com/youniaogu/MangaReader/releases/tag/v0.6.8) fixed

**Comment by rowenahxt** [comment]
这个bug还有可以复现的，打开任意一个漫画的倒数第二话，通过下滑进入最后一话，长按左侧上一话，再长按右侧下一话会报同样的错误

**Comment by youniaogu** [comment]
[v0.7.0](https://github.com/youniaogu/MangaReader/releases/tag/v0.7.0) fixed
