### ISSUE TITLE
插件网站

### ISSUE THREAD

**Issue by MeladyC2e** [youniaogu/MangaReader#81]
**现有功能改进还是新功能/插件提议？**

**请简单描述下你的需求**

**解决方案**

希望增加漫画狗这个网站: https://dogemanga.com/
算是比较全的漫画网站了，如果能加上收藏功能，记录观看的地方就好了，期待老大的更新

**Comment by youniaogu** [comment]
非常抱歉，去看了下感觉质量一般，有些漫画重复图片错误的问题
