### ISSUE TITLE
安装时提示“包含病毒 a.gray.bulimiatgen.h”

### ISSUE THREAD

**Issue by f-s2** [youniaogu/MangaReader#82]
**非常感谢您填写错误报告！**

**以下是一些注意事项，请务必阅读**

- 提交报告前请检索相关 issues，避免重复提问
- 提交报告前请先尝试浏览器里访问原网站排除网络问题
- 请按下边 issues 模板要求提供相关信息，避免挤牙膏式提问

---

**问题描述**

大佬麻烦问下安装应用时提示 “该应用包含病毒 a.gray.bulimiatgen.h”，是什么原因导致的呀

**如何复现**

安装 app

**错误信息**

该应用包含病毒 a.gray.bulimiatgen.h

**设备信息**

Redmi k50 Pro v0.6.7

**Comment by youniaogu** [comment]
搜了下，似乎是安卓debugger报的，并不是病毒

**Comment by OwenLinZero** [comment]
0.7.3 版本，三星 OneUI 安装同样报安全问题。
