### ISSUE TITLE
拷贝源线路问题

### ISSUE THREAD

**Issue by shibuyameltdown** [youniaogu/MangaReader#83]
拷贝应该是有大陆线路和海外线路的
现在的拷贝源感觉不太稳定（？）
经常需要在裸连/香港/日本节点中间切才能正常看，不然就很难加载出来。
顺带一提，经常会出现看着看着中间有一页就没加载出来，需要手动点一下重载，不太清楚是我梯子问题还是别的

**Comment by youniaogu** [comment]
拷贝最近换了域名，下个版本会改

**Comment by youniaogu** [comment]
[v0.6.8](https://github.com/youniaogu/MangaReader/releases/tag/v0.6.8) 已更新

**Comment by hot36952** [comment]
今天拷贝源似乎挂了。
