### ISSUE TITLE
音量键翻页导致静音

### ISSUE THREAD

**Issue by ztszts777** [youniaogu/MangaReader#84]
在APP内想调一下音量，但是锁定了音量翻页不能关闭，且按下音量键后会直接静音
matepadpro13.2

**Comment by youniaogu** [comment]
没复现出来，你用的版本是多少，可以说下更详细的复现步骤吗

**Comment by ztszts777** [comment]
最新版的0.6.7，
步骤为打开网易云，开音乐放后台然后音量键翻页
这次我也没复现出来，这次是，举例：按音量键翻下一页后，音量减小一下，然后恢复减小之前的音量
导致音量键翻页使音乐音量坐过山车
也就是没有关闭音量键的调音量功能

然后我也不想要音量键翻页的功能，只是想调下音量，也不能调
建议加个音量键翻页的功能开关放设置里

**Comment by youniaogu** [comment]
说实话我自己用的也少，所以有些场景可能会没覆盖到

下个版本更新增加音量翻页开关按钮

**Comment by ztszts777** [comment]
感谢

**Comment by youniaogu** [comment]
[v0.6.8](https://github.com/youniaogu/MangaReader/releases/tag/v0.6.8) 已更新
