### ISSUE TITLE
频繁出现“数据格式错误”的提示

### ISSUE THREAD

**Issue by rxw22** [youniaogu/MangaReader#86]
**非常感谢您填写错误报告！**

**以下是一些注意事项，请务必阅读**

- 提交报告前请检索相关 issues，避免重复提问
- 提交报告前请先尝试浏览器里访问原网站排除网络问题
- 请按下边 issues 模板要求提供相关信息，避免挤牙膏式提问

---

**问题描述**
应用主界面底部频繁出现“数据格式错误”的提示，不确定是我网络的问题还是bug
**如何复现**
我卸载后重装，提示消失，目前没能找到复现方法

**错误信息**
“数据格式错误”

**设备信息**
魅族17
android 13 
app版本v0.6.7

**Comment by youniaogu** [comment]
`数据格式错误` 确定是这个文案吗，这个文案只有恢复数据时才会出现

会不会是其他的 `同步xxxx失败：格式错误`

**Comment by youniaogu** [comment]
缺少复现信息
