### ISSUE TITLE
包子漫画平台的条漫页数超过50（即网页页数超过1）显示不全

### ISSUE THREAD

**Issue by rowenahxt** [youniaogu/MangaReader#87]
包子漫画平台的条漫章节页数超过50（即网页页数超过1），app内章节只会显示前50页（即网页内第一页的内容）

比如https://www.fzmanga.com/comic/chapter/zhegehunfanzhengyeyaowandan-kimchachachokamcheonggwa_h2sz9u/0_2.html 总计3页，app内只显示第一页内容

**Comment by rowenahxt** [comment]
感谢，辛苦了

**Comment by youniaogu** [comment]
已修复 [v0.6.9](https://github.com/youniaogu/MangaReader/releases/tag/v0.6.9)
