### ISSUE TITLE
「在瀏覽器中打開」無效

### ISSUE THREAD

**Issue by kenwang92** [youniaogu/MangaReader#88]
**非常感谢您填写错误报告！**

**以下是一些注意事项，请务必阅读**

- 提交报告前请检索相关 issues，避免重复提问
- 提交报告前请先尝试浏览器里访问原网站排除网络问题
- 请按下边 issues 模板要求提供相关信息，避免挤牙膏式提问

---

**问题描述**

1.「在瀏覽器中打開」的按鈕按了沒有反應，沒有彈出內嵌式瀏覽器，沒有任何訊息
https://github.com/youniaogu/MangaReader/assets/51316165/b4b00640-5f6e-4c9a-ba68-52cefb7afb97
2.左上角的about按鈕中，按下apk下載按鈕沒有反應
3.按下備份按鈕後，備份到google雲端硬碟中，更新app後恢復上個版本的備份顯示此圖（新版本當下備份後恢復沒問題）
![Screenshot_20231221-102224](https://github.com/youniaogu/MangaReader/assets/51316165/2bf0d8c8-3788-4328-8daa-4c444e25bf8d)

**如何复现**

1. 剛下載apk時可以正常打開瀏覽器，中途經過一次更新後無法使用，想說再等幾個更新應該會正常，但是經過3個版本更新沒有解決，故來此提出建議
2. 印象中一直都無法使用，總是到github下載apk後安裝

**错误信息**

無任何錯誤訊息

**设备信息**

設備：oneplus 1+6t
app版本：v0.6.8

**Comment by youniaogu** [comment]
1. IOS 是可以的，可能跟安卓权限有关，你可以去检查下，是不是代码上的 bug 我要回去拿安卓手机测试下
2. 和第一条一样
3. 是 bug，下个版本修复

每次更新我只对经常用到的功能做回归测试，而且我主力机不是安卓，没法覆盖到所有场景

所以如果你遇到问题，直接上来提 issues 就好了（模版信息能填就填），我都会回复的，不过要到晚上或周六日才会处理

**Comment by kenwang92** [comment]
請問打開app沒有要求任何權限，該如何給權限呢？
目前app的權限狀態如下
![Screenshot_20231221-133328](https://github.com/youniaogu/MangaReader/assets/51316165/27edc2ae-b752-4e75-afd5-dd718ce981e5)

**Comment by youniaogu** [comment]
@kenwang92 刚测试安卓确实不行，是个 bug

**Comment by kenwang92** [comment]
謝謝測試，辛苦了

**Comment by youniaogu** [comment]
已修复，[v0.6.9](https://github.com/youniaogu/MangaReader/releases/tag/v0.6.9)
