### ISSUE TITLE
希望可以增加阅读方向选择还有手动选择其他源的同本漫画

### ISSUE THREAD

**Issue by XianYuDaXian** [youniaogu/MangaReader#9]
从右到左更符合日漫的阅读方式，还有就是手动指定其它源的同款漫画和在指定的源之间切换，类似这样做了一个示例图
![86F760E1-87E5-4688-99C9-7A5A5DBC344B](https://user-images.githubusercontent.com/20138259/201522690-125b43a8-3b95-4f03-91ac-acb27554d686.png)

**Comment by VCE1** [comment]
还有一个ui的问题，在ipad上不能完整显示
![3H_P@3@6RMZ@NILYB@2GP6M](https://user-images.githubusercontent.com/79588027/201522992-e54638bd-5d37-4578-a03b-af456b61a332.jpg)

一行只有三本漫画显得太大，建议添加更多的布局。

而且在左右滑动阅读的时候不能适应屏幕。
![2](https://user-images.githubusercontent.com/79588027/201523143-debb1a68-d436-4f52-81f7-633c9bef39ab.gif)

**Comment by youniaogu** [comment]
@XianYuDaXian 相同漫画不同源之间交集很少，比较难关联起来，可以考虑其他实现需求的方向（比如跳到搜索页面）。然后阅读方向这块我会加到后面的更新里

**Comment by youniaogu** [comment]
@VCE1 开发时候没注意适配平板这块，后面我会修改自适应这块

**Comment by XianYuDaXian** [comment]
> @XianYuDaXian 相同漫画不同源之间交集很少，比较难关联起来，可以考虑其他实现需求的方向（比如跳到搜索页面）。然后阅读方向这块我会加到后面的更新里

可能我表达不清晰 我的意思是手动将不同源的同本漫画关联起来 不是说程序自动关联 比如说我将这里的三本合成一本 然后我点进去的时候可以 切换源并且指定更多的源 
![A3A872C8-DF47-4C71-80F5-19E3F72D6241](https://user-images.githubusercontent.com/20138259/201557148-757d2506-73ad-424a-a5d4-0a694d75ebe5.png)

**Comment by youniaogu** [comment]
书本合并评估了下，感觉使用场景不大，对比工作量有点得不偿失

还有一点是会跟更新提醒有冲突，非常抱歉

<img width="240" src="https://user-images.githubusercontent.com/13073995/201559251-9907954c-e16f-42c9-b5bf-1d96ba72c561.jpg" />

**Comment by youniaogu** [comment]
阅读方向切换以及ipad不适配屏幕的问题已更新至 [v0.3.0](https://github.com/youniaogu/MangaReader/releases/tag/v0.3.0)

如后续还有问题，欢迎反馈

**Comment by XianYuDaXian** [comment]
谢谢作者的更新 阅读方向使用没有问题 这些天使用下来 发现有一个bug就是当漫画加载不出来的时候 必须要等待它加载出来 不然加载失败的话 无法退出阅读界面 只能尝试重新加载 但还是不行的话这时候就只能强制关闭应用
![69081169-50DF-493A-9302-9E8B02045E8D](https://user-images.githubusercontent.com/20138259/203675544-1d592de1-fa56-456f-924d-c3cf4eb37fb7.png)

**Comment by youniaogu** [comment]
@XianYuDaXian 你是苹果设备吧，试下屏幕最左边往右滑，应该是可以的
