### ISSUE TITLE
加快取得cloudflare 校验頁面的過程

### ISSUE THREAD

**Issue by kenwang92** [youniaogu/MangaReader#90]
**现有功能改进还是新功能/插件提议？**

**请简单描述下你的需求**

批量刷新漫畫時需要經過多層菜單抵達取得cloudflare 校验的頁面

https://github.com/youniaogu/MangaReader/assets/51316165/5f3aeb24-7399-4972-95e2-75b3ffe4b7c6

**解决方案**
希望能長按批量刷新按鈕直接跳出此頁面（私心希望此頁面可以調整順序或隱藏選項）
![Screenshot_20231221-134419](https://github.com/youniaogu/MangaReader/assets/51316165/242b0752-8970-456a-9218-067697354a8a)
另一種方法是當批量刷新到token失敗的漫畫直接跳出cloudflare驗證webview，個人偏好這種方法。
感謝大佬

**Comment by youniaogu** [comment]
Home 页加个按钮跳转吧

**Comment by youniaogu** [comment]
[v0.6.9](https://github.com/youniaogu/MangaReader/releases/tag/v0.6.9)
