### ISSUE TITLE
可以考虑一下这个资源站点吗

### ISSUE THREAD

**Issue by rowenahxt** [youniaogu/MangaReader#91]
https://m.happymh.com/，有cloudflare验证

**Comment by youniaogu** [comment]
打不开，网站服务器炸了...

**Comment by rowenahxt** [comment]
![IMG_2481](https://github.com/youniaogu/MangaReader/assets/26662830/3ca98ba1-6083-4136-b98a-475295b2ea8f)
我可以正常使用诶，是这个原因吗😂我使用了蛮久感觉挺稳定

**Comment by youniaogu** [comment]
可以打开，我刚忘记挂代理了

看起来挺不错的，暂定下个版本更新

**Comment by Letter0** [comment]
哇我刚想发个帖子说这个网站也很好，想推荐作者大大加上这个网站的链接，就看到你已经提出来了👍

**Comment by youniaogu** [comment]
[v0.7.0](https://github.com/youniaogu/MangaReader/releases/tag/v0.7.0) done
