### ISSUE TITLE
关于漫画打开白屏但是保存图片可以在照片中正常查看的问题

### ISSUE THREAD

**Issue by Missile-gh** [youniaogu/MangaReader#92]
**非常感谢您填写错误报告！**

**以下是一些注意事项，请务必阅读**

- 提交报告前请检索相关 issues，避免重复提问
- 提交报告前请先尝试浏览器里访问原网站排除网络问题
- 请按下边 issues 模板要求提供相关信息，避免挤牙膏式提问

---

**问题描述**
漫画打开白屏但是保存图片可以在照片中正常查看，
**如何复现**
0.6.5版本正常，后续版本均出现打开漫画白屏现象

**错误信息**
![IMG_2181](https://github.com/youniaogu/MangaReader/assets/155232356/fb0fb5ea-4090-4bbb-ba75-e769ca4b3954)

**设备信息**
ipad pro 2018 ipados13.5
v0.6.6至v0.6.8均有此现象

**Comment by youniaogu** [comment]
这是哪个插件的哪个漫画，还是说 ipad 都会白屏？

**Comment by Missile-gh** [comment]
拷贝的，追的好几个都是这样，截图的是邻家天使的漫画，长按保存图片在照片app里面能正常显示画面

**Comment by youniaogu** [comment]
拷贝里没搜到 “邻家天使” 这个漫画，可以截图下漫画的详情页吗

**Comment by Missile-gh** [comment]
![IMG_2184](https://github.com/youniaogu/MangaReader/assets/155232356/39cc877a-fa9f-49b3-9d52-0836b4cb8623)
拷贝的其他漫画也都是白屏黑屏

**Comment by Missile-gh** [comment]
手机上的iphone8plus ios13.5.1 也会出现一样的问题呢

**Comment by youniaogu** [comment]
其他插件会有这个问题吗

**Comment by Missile-gh** [comment]
试了KL的2个，一个可以显示，一个也是白屏的（不知道是不是网络慢），包子漫画试了几个也可以正常显示

**Comment by youniaogu** [comment]
你 ios 版本太低，需要 ios14 才能支持 webp 格式的图片（保存图片会转成 png，所以能看）

<img width="775" alt="image" src="https://github.com/youniaogu/MangaReader/assets/13073995/1aada9b2-888a-4ade-9760-2893218dca12">

v0.6.6 后我把拷贝漫画的图片[修改到了 webp](https://github.com/youniaogu/MangaReader/compare/v0.6.5...v0.6.6#diff-3ed93b37953ef9a4ff330effb993ba0bc06bfdfbbdaa36ea7d7ca57dbddab54fR236)，所以你更新后才会不显示

建议你升级到 ios14，因为 webp 格式现在已经运用很广泛了

而且就算我把拷贝漫画修改回 png，其他插件网站也会有用 webp 格式的

**Comment by youniaogu** [comment]
不过下个版本我会改回 png，但其他插件的就没法修改了

**Comment by Missile-gh** [comment]
原来如此，十分感谢解答！（先用旧版本看了

**Comment by youniaogu** [comment]
@Missile-gh 已更新 [v0.6.9](https://github.com/youniaogu/MangaReader/releases/tag/v0.6.9) https://github.com/youniaogu/MangaReader/commit/a44c6f393d8ef78e4575f9382b36ce3700f4c530#
