### ISSUE TITLE
漫畫詳情頁面右側有紅色條紋

### ISSUE THREAD

**Issue by kenwang92** [youniaogu/MangaReader#94]
**非常感谢您填写错误报告！**

**以下是一些注意事项，请务必阅读**

- 提交报告前请检索相关 issues，避免重复提问
- 提交报告前请先尝试浏览器里访问原网站排除网络问题
- 请按下边 issues 模板要求提供相关信息，避免挤牙膏式提问

---

**问题描述**

漫畫詳情頁面右側有紅色條紋

**如何复现**

自app更新至v0.6.9之後

https://github.com/youniaogu/MangaReader/assets/51316165/6adce6fe-bc8a-4357-8f5f-7dc099f1c3e7

**错误信息**

無任何錯誤訊息

**设备信息**

設備：oneplus 1+6t
app版本：v0.6.9

**Comment by youniaogu** [comment]
已修复
