### ISSUE TITLE
ipa在altstore中侧载报错

### ISSUE THREAD

**Issue by RhettButlerX** [youniaogu/MangaReader#95]
**问题描述**

大佬你好，使用下载的ipa在altstore中侧载时报错，无法成功。试验了0.6.8与0.6.9两个版本，错误信息相同。

**如何复现**

在altstore中选择+按钮，选择下载的ipa文件。侧载中途报错。其他ipa可以正常侧载。侧载数量没有超过3个。

**错误信息**

```
/Users/rileytestut/Developer/Projects/AltStore/Dependencies/AltSign/AltSign/ldid/../../Dependencies/ldid/ldid.cpp(2435): _assert(): target.sputn(data, writ) == writ
```

![b907b29e19ed91f8affbc2a9e03cffc](https://github.com/youniaogu/MangaReader/assets/20549449/cf502f0f-c968-49f3-af7a-54bf11a11731)
![d413d69e3c1e0f4fd48dc0dcdab7758](https://github.com/youniaogu/MangaReader/assets/20549449/f6a85485-c1ee-4be3-b822-4ea638669d5e)

**设备信息**

iphoneXR iOS 17.1.2
altstore 1.7
mangareader 0.6.8/0.6.9

**Comment by youniaogu** [comment]
一般我都是 xcode 直接装的，没有测试 altstore，等有空我去测试下

**Comment by youniaogu** [comment]
我这边安装（0.6.9）没问题，应该是 altstore 的问题

<img width="300" src="https://github.com/youniaogu/MangaReader/assets/13073995/3952e401-e78a-4515-bb3a-d7102edeb87f" />

**Comment by RhettButlerX** [comment]
我今天又试了下，又可以了，虽然安装比较慢，但是可以装上了，感谢回复。
