### ISSUE TITLE
希望能簡單查看評論

### ISSUE THREAD

**Issue by kenwang92** [youniaogu/MangaReader#97]
**现有功能改进还是新功能/插件提议？**

新功能提议

**请简单描述下你的需求**

希望"在瀏覽器中打開"按鈕可以選擇直接跳轉到評論區頁面，或是將評論區爬下來於app中觀看，不需有發評論的功能，主要是想看幾條評論避免踩雷，目前查看評論的方式略微繁瑣

https://github.com/youniaogu/MangaReader/assets/51316165/aa7db769-d1b8-4b0e-a51e-2cb34f78aab3

**解决方案**

右下角多一個懸浮按鈕,可查看評論
![image](https://github.com/youniaogu/MangaReader/assets/51316165/45c01146-efb4-4bda-8102-1bc13f86e691)

**Comment by youniaogu** [comment]
不是每个网站都有评论的，所以没法作为一个通用功能添加

**Comment by kenwang92** [comment]
謝謝回覆，但是我覺得copy作為預設站點且資源算多是可以添加為功能的，畢竟只是作為選擇漫畫的參考？(個人看法)，其他網站需要代理或cloudflare可能不適合適配，或是僅添加自定義"在瀏覽器中打開"按鈕可以選擇直接跳轉到評論區頁面(僅url變化)的功能

**Comment by youniaogu** [comment]
@kenwang92 有点太定制化了，其实“在瀏覽器中打開”按钮只是拿来 debug 的，确认网站有没有问题的而已，非常抱歉
