### ISSUE TITLE
包子漫画页数显示问题

### ISSUE THREAD

**Issue by soulmatelh** [youniaogu/MangaReader#98]
**非常感谢您填写错误报告！**

**以下是一些注意事项，请务必阅读**

- 提交报告前请检索相关 issues，避免重复提问
- 提交报告前请先尝试浏览器里访问原网站排除网络问题
- 请按下边 issues 模板要求提供相关信息，避免挤牙膏式提问

---

**问题描述**
我看了之前的issues，但是还存在这个问题
包子漫画平台的条漫页数超过50（即网页页数超过1）显示不全

**如何复现**
软件内任何一个包子漫画的书籍超过50页后都无法显示下一页，在网页上有3页

https://cn.czmanga.com/comic/chapter/zhangmendidiaodian-yuewenmanhua/0_315_3.html

**错误信息**

![IMG_4776](https://github.com/youniaogu/MangaReader/assets/56060453/691b0572-f9ce-4b30-a4f5-779de586634e)

![IMG_4759](https://github.com/youniaogu/MangaReader/assets/56060453/841b5362-976c-47bb-9404-a7f12b4e1c2f)

**设备信息**

v0.6.9

**Comment by youniaogu** [comment]
[v0.7.0](https://github.com/youniaogu/MangaReader/releases/tag/v0.7.0) fixed
