### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by HongxiuRumeng** [youniaogu/MangaReader#99]
软件状态栏目前不能沉浸影响使用体验，部分机型虚拟按键也不能沉浸，在找到对应漫画后，漫画的标题也没有复制功能，不能分享给朋友

**Comment by youniaogu** [comment]
+ 状态栏阅读的时候是可以隐藏的
+ 安卓虚拟按键得系统里关闭，改用手势
+ 分享功能暂时没有

**Comment by youniaogu** [comment]
不考虑分享功能，非常抱歉
